(()=>{
'use strict';
const KEY='cl30_engagement';
const dayKey=()=>new Date().toISOString().slice(0,10);
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
const state={day:saved.day||dayKey(),baseLevel:+saved.baseLevel||0,dailyDone:!!saved.dailyDone,seen:Array.isArray(saved.seen)?saved.seen:[]};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function ensureDay(level){const d=dayKey();if(state.day!==d){state.day=d;state.baseLevel=Math.max(1,level||1);state.dailyDone=false;save()}else if(!state.baseLevel){state.baseLevel=Math.max(1,level||1);save()}}
const style=document.createElement('style');style.textContent=`
.v30-launch{font-size:18px!important}.v30-overlay{position:fixed;inset:0;z-index:7200;display:none;place-items:center;padding:18px;background:rgba(0,5,10,.78);backdrop-filter:blur(14px)}.v30-overlay.show{display:grid}.v30-sheet{width:min(440px,94vw);max-height:82vh;overflow:auto;border-radius:24px;padding:20px;background:linear-gradient(180deg,#091825,#06101a);border:1px solid rgba(112,225,255,.2);box-shadow:0 30px 100px rgba(0,0,0,.55)}.v30-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v30-head h2{margin:0;font-size:22px}.v30-head p{margin:5px 0 0;font-size:11px;opacity:.6}.v30-close{border:0;background:rgba(255,255,255,.06);color:white;width:34px;height:34px;border-radius:50%;font-size:20px}.v30-daily{margin:16px 0;padding:14px;border-radius:16px;background:linear-gradient(135deg,rgba(80,220,255,.1),rgba(166,109,255,.08));border:1px solid rgba(120,220,255,.14)}.v30-daily small{opacity:.55;letter-spacing:.12em}.v30-daily b{display:block;margin:5px 0 8px}.v30-progress{height:7px;background:rgba(255,255,255,.07);border-radius:99px;overflow:hidden}.v30-progress i{display:block;height:100%;background:linear-gradient(90deg,#62e5ff,#a66dff);width:0}.v30-ach{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v30-card{padding:11px;border-radius:14px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.05);min-height:68px}.v30-card.locked{opacity:.42}.v30-card b{font-size:12px;display:block}.v30-card span{font-size:10px;opacity:.65;display:block;margin-top:4px}.v30-card em{font-style:normal;font-size:9px;color:#7fe9ff}.v30-toast{position:fixed;left:50%;bottom:max(24px,env(safe-area-inset-bottom));z-index:7300;transform:translate(-50%,12px);opacity:0;padding:10px 14px;border-radius:999px;background:#071722;border:1px solid rgba(126,233,255,.2);color:#dffbff;font-size:11px;font-weight:800;transition:.22s}.v30-toast.show{opacity:1;transform:translate(-50%,0)}
`;document.head.appendChild(style);
const tools=document.querySelector('.tools');if(!tools)return;
const btn=document.createElement('button');btn.type='button';btn.className='icon-btn v30-launch';btn.title='Щоденна лабораторія';btn.textContent='◎';tools.prepend(btn);
const ov=document.createElement('div');ov.className='v30-overlay';ov.innerHTML='<div class="v30-sheet"><div class="v30-head"><div><h2>Щоденна лабораторія</h2><p>Малі цілі, що ведуть до 118 / 118</p></div><button class="v30-close">×</button></div><div class="v30-daily"></div><h3 style="font-size:13px;margin:14px 0 8px">Досягнення</h3><div class="v30-ach"></div></div>';document.body.appendChild(ov);
const toast=document.createElement('div');toast.className='v30-toast';document.body.appendChild(toast);function ping(t){toast.textContent=t;toast.classList.add('show');clearTimeout(ping.t);ping.t=setTimeout(()=>toast.classList.remove('show'),2200)}
const defs=[['e5','Перші відкриття','Відкрити 5 елементів',s=>s.discovered.length>=5],['e10','Колекціонер','Відкрити 10 елементів',s=>s.discovered.length>=10],['e25','Дослідник матерії','Відкрити 25 елементів',s=>s.discovered.length>=25],['r1','Перший синтез','Відкрити 1 рецепт',s=>s.recipes.length>=1],['a1','Артефакт знайдено','Знайти 1 артефакт',s=>s.artifacts.length>=1],['l5','Серія дослідів','Дійти до досліду 5',s=>s.level>=5],['l10','Лаборант','Дійти до досліду 10',s=>s.level>=10],['l25','Старший дослідник','Дійти до досліду 25',s=>s.level>=25]];
let last={level:1,discovered:[],recipes:[],artifacts:[]};
function normalize(s){return{level:+s?.level||1,discovered:Array.isArray(s?.discovered)?s.discovered:[],recipes:Array.isArray(s?.recipes)?s.recipes:[],artifacts:Array.isArray(s?.artifacts)?s.artifacts:[]}}
function evaluate(s){ensureDay(s.level);if(!state.dailyDone&&s.level>state.baseLevel){state.dailyDone=true;save();ping('Щоденний дослід виконано ✓')}for(const [id,title,,ok] of defs){if(ok(s)&&!state.seen.includes(id)){state.seen.push(id);save();ping(`Досягнення: ${title}`)}}}
function paint(){const s=last;ensureDay(s.level);const done=state.dailyDone,delta=Math.max(0,s.level-state.baseLevel);ov.querySelector('.v30-daily').innerHTML=`<small>СЬОГОДНІ</small><b>${done?'Дослід завершено':'Заверши 1 новий дослід'}</b><div class="v30-progress"><i style="width:${done||delta>0?100:0}%"></i></div><span style="display:block;margin-top:7px;font-size:10px;opacity:.65">${done?'Серія дня зафіксована':'Пройди наступний рівень, не змінюючи основний прогрес кампанії'}</span>`;const box=ov.querySelector('.v30-ach');box.innerHTML='';for(const [id,title,desc,ok] of defs){const unlocked=ok(s),el=document.createElement('div');el.className='v30-card '+(unlocked?'':'locked');el.innerHTML=`<em>${unlocked?'ВІДКРИТО':'ЗАБЛОКОВАНО'}</em><b>${title}</b><span>${desc}</span>`;box.appendChild(el)}}
window.addEventListener('chemlab:state',e=>{last=normalize(e.detail);evaluate(last);if(ov.classList.contains('show'))paint()});
try{last=normalize(window.ChemLab27?.getState?.()||{});evaluate(last)}catch{}
btn.onclick=()=>{paint();ov.classList.add('show')};ov.querySelector('.v30-close').onclick=()=>ov.classList.remove('show');ov.onclick=e=>{if(e.target===ov)ov.classList.remove('show')};
})();