(()=>{
const CAP=4;
const E={ruby:{s:'Na',n:'Натрій',c:'#ff535d',c2:'#ff8c94'},emerald:{s:'Cl',n:'Хлор',c:'#35e68b',c2:'#79f2b1'},citrine:{s:'Fe',n:'Ферум',c:'#ffb43f',c2:'#ffd071'},sapphire:{s:'O',n:'Кисень',c:'#20b9ff',c2:'#64d4ff'},amethyst:{s:'C',n:'Карбон',c:'#9c57f6',c2:'#c18cff'},frost:{s:'H',n:'Гідроген',c:'#4fe0e7',c2:'#92f0f3'},rose:{s:'Au',n:'Аурум',c:'#ffd84d',c2:'#fff08e'}};
const ORDER=['ruby','emerald','citrine','sapphire','amethyst','frost','rose'];
const MILESTONES=[[1,'ruby'],[1,'emerald'],[1,'citrine'],[4,'sapphire'],[8,'amethyst'],[12,'frost'],[16,'rose']];
const RANKS=[{x:0,n:'Учень алхімік'},{x:120,n:'Лаборант'},{x:350,n:'Хімік'},{x:800,n:'Магістр реакцій'},{x:1600,n:'Архіалхімік'}];
const REACTIONS=[{formula:'NaCl',name:'Хлорид натрію',eq:'2Na + Cl₂ → 2NaCl',need:['Na','Cl']},{formula:'H₂O',name:'Вода',eq:'2H₂ + O₂ → 2H₂O',need:['H','O']},{formula:'Fe₂O₃',name:'Оксид заліза(III)',eq:'4Fe + 3O₂ → 2Fe₂O₃',need:['Fe','O']},{formula:'CO₂',name:'Діоксид карбону',eq:'C + O₂ → CO₂',need:['C','O']}];
const SECRETS=[
 {pair:['Na','Cl'],kind:'crystal',title:'СЕКРЕТ: КРИСТАЛІЗАЦІЯ',bonus:28,fx:'#b7fff0',artifact:'Кристал солі'},
 {pair:['H','O'],kind:'flash',title:'СЕКРЕТ: ЕНЕРГЕТИЧНИЙ СПАЛАХ',bonus:35,fx:'#7ee9ff',artifact:'Плазмовий уламок'},
 {pair:['Fe','O'],kind:'crystal',title:'СЕКРЕТ: ОКСИДНИЙ КРИСТАЛ',bonus:32,fx:'#ff9f42',artifact:'Оксидний фрагмент'},
 {pair:['C','O'],kind:'burst',title:'СЕКРЕТ: ВУГЛЕЦЕВИЙ ІМПУЛЬС',bonus:30,fx:'#b86cff',artifact:'Темний каталізатор'}
];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
let S={level:+localStorage.cl9_level||1,gold:+localStorage.cl9_gold||0,nug:+localStorage.cl9_nug||0,xp:+localStorage.cl9_xp||0,unlocked:[],tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:localStorage.cl9_muted==='1',par:0,reactionStep:0,reactionIndex:+localStorage.cl14_reaction||0,artifacts:[]};
try{S.artifacts=JSON.parse(localStorage.cl15_artifacts||'[]')}catch{}
function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function save(){localStorage.cl9_level=S.level;localStorage.cl9_gold=S.gold;localStorage.cl9_nug=S.nug;localStorage.cl9_xp=S.xp;localStorage.cl9_unlock=JSON.stringify(S.unlocked);localStorage.cl14_reaction=S.reactionIndex;localStorage.cl15_artifacts=JSON.stringify(S.artifacts);$('gold').textContent=S.gold;$('nugget').textContent=S.nug}
function syncUnlocks(){let saved=[];try{saved=JSON.parse(localStorage.cl9_unlock||'[]')}catch{};const should=MILESTONES.filter(([l])=>S.level>=l).map(([,k])=>k);S.unlocked=[...new Set([...ORDER.slice(0,3),...saved.filter(k=>ORDER.includes(k)),...should])].sort((a,b)=>ORDER.indexOf(a)-ORDER.indexOf(b));save()}
function topRun(t){if(!t.length)return 0;const x=t.at(-1);let n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}
function legal(T,a,b){const A=T[a],B=T[b];if(a===b||!A?.length||!B||B.length>=CAP)return 0;const x=A.at(-1);if(B.length&&B.at(-1)!==x)return 0;return Math.min(topRun(A),CAP-B.length)}
function cleared(){return S.tubes.every(t=>t.length===0)}
function rng(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}
function activeColors(){const count=Math.min(3+Math.floor((S.level-1)/4),S.unlocked.length,5);return S.unlocked.slice(0,count)}
function build(seedOffset=0){const colors=activeColors(),r=rng(S.level*7919+seedOffset*104729+31),T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);let steps=14+colors.length*5+Math.min(S.level,8);for(let s=0;s<steps;s++){const cand=[];for(let a=0;a<T.length;a++){if(!T[a].length)continue;const run=topRun(T[a]),x=T[a].at(-1);for(let b=0;b<T.length;b++){if(a===b||T[b].length>=CAP)continue;if(T[b].length&&T[b].at(-1)===x)continue;for(let n=1;n<=Math.min(run,CAP-T[b].length);n++)cand.push([a,b,n])}}if(!cand.length)break;const m=cand[Math.floor(r()*cand.length)];for(let i=0;i<m[2];i++)T[m[1]].push(T[m[0]].pop())}S.par=steps;return T}
function rankUI(){let r=RANKS[0];for(const x of RANKS)if(S.xp>=x.x)r=x;const i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function bubbles(layer){for(let i=0;i<3;i++){const b=document.createElement('i');b.className='bubble';const z=2+Math.random()*3;b.style.width=b.style.height=z+'px';b.style.left=(12+Math.random()*74)+'%';b.style.setProperty('--dur',(2.5+Math.random()*2.4)+'s');b.style.setProperty('--delay',(-Math.random()*2)+'s');b.style.setProperty('--travel',(22+Math.random()*28)+'px');b.style.setProperty('--drift',(-4+Math.random()*8)+'px');layer.appendChild(b)}}
function reaction(){const syms=new Set(S.unlocked.map(k=>E[k].s)),available=REACTIONS.filter(r=>r.need.every(x=>syms.has(x)));if(!available.length)return REACTIONS[0];S.reactionIndex%=available.length;return available[S.reactionIndex]}
function stationUI(){const r=reaction(),box=$('recipe');if(!box)return;box.innerHTML='';r.need.forEach((sym,i)=>{if(i){const p=document.createElement('span');p.className='arrow';p.textContent='+';box.appendChild(p)}const s=document.createElement('div');s.className='slot '+(i<S.reactionStep?'done':i===S.reactionStep?'next':'');s.textContent=sym;box.appendChild(s)});const ar=document.createElement('span');ar.className='arrow';ar.textContent='→';box.appendChild(ar);const p=document.createElement('div');p.className='slot product';p.textContent=r.formula;box.appendChild(p);$('stationText').innerHTML=`${r.eq}<br><span style="opacity:.72">Продукт: ${r.name}</span>`}
function render(){const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(S.sel>=0&&i!==S.sel){const sec=secretFor(S.sel,i);el.className+=(legal(S.tubes,S.sel,i)||sec)?' valid':' dim'}const inn=document.createElement('div');inn.className='tube-inner';tube.forEach((k,li)=>{const e=E[k],d=document.createElement('div');d.className='layer';d.style.bottom=`calc(5px + ${li} * ((100% - 12px)/4))`;d.style.background=`linear-gradient(180deg,${e.c2},${e.c})`;d.style.setProperty('--glow',e.c+'66');d.textContent=e.s;bubbles(d);inn.appendChild(d)});el.appendChild(inn);wrap.appendChild(el);wrap.addEventListener('pointerup',ev=>{ev.preventDefault();tap(i)},{passive:false});board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;$('levelSub').textContent='Реагенти: '+[...new Set(S.tubes.flat())].map(k=>E[k].s).join(', ');$('footerLevel').textContent=`Рівень ${S.level} з 50 ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();stationUI();save()}
function start(level){S.level=Math.max(1,level);syncUnlocks();S.tubes=build();S.sel=-1;S.hist=[];S.moves=Math.max(22,S.par+12);S.undo=3;S.shuffle=3;S.hints=3;S.extra=false;S.busy=false;render()}
function makeStream(x1,y1,x2,y2,color,duration=900){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','liquid-stream-svg');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','liquid-stream-path');p.style.setProperty('--pourColor',color);p.setAttribute('d',`M ${x1} ${y1} C ${x1} ${y1+44}, ${x2} ${y2-35}, ${x2} ${y2}`);svg.appendChild(p);document.body.appendChild(svg);const len=p.getTotalLength();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;p.animate([{strokeDashoffset:len,opacity:0},{strokeDashoffset:0,opacity:1,offset:.22},{strokeDashoffset:0,opacity:1,offset:.78},{strokeDashoffset:-len*.25,opacity:0}],{duration,easing:'ease-in-out'});setTimeout(()=>svg.remove(),duration+100)}
function animatePour(a,b,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst||!src.animate){done();return}const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=B.left>A.left?1:-1,g=src.cloneNode(true);g.className='tube pour-ghost';Object.assign(g.style,{left:A.left+'px',top:A.top+'px',width:A.width+'px',height:A.height+'px'});document.body.appendChild(g);src.style.opacity='.12';const dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*10,dy=(B.top-A.top)-A.height*.42,tilt=dir*68;const duration=1650;const an=g.animate([{transform:'translate3d(0,0,0) rotate(0)',offset:0},{transform:`translate3d(${dx*.55}px,${dy*.48}px,0) rotate(${tilt*.18}deg)`,offset:.25},{transform:`translate3d(${dx}px,${dy}px,0) rotate(${tilt}deg)`,offset:.48},{transform:`translate3d(${dx}px,${dy+2}px,0) rotate(${tilt}deg)`,offset:.76},{transform:`translate3d(${dx*.6}px,${dy*.5}px,0) rotate(${tilt*.2}deg)`,offset:.9},{transform:'translate3d(0,0,0) rotate(0)',offset:1}],{duration,easing:'cubic-bezier(.18,.72,.18,1)',fill:'forwards'});setTimeout(()=>{const x=B.left+B.width/2,y=B.top+8;makeStream(x-dir*18,y-70,x,y,color,850);dst.classList.add('receiving');setTimeout(()=>dst.classList.remove('receiving'),900)},700);Promise.resolve(an.finished).catch(()=>{}).finally(()=>{src.style.opacity='';g.remove();done()})}
function fxAt(i,color,kind='burst'){const tube=document.querySelectorAll('.tube')[i];if(!tube)return;const r=tube.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height*.45;const ring=document.createElement('i');ring.className='reaction-fx reaction-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--fx',color);document.body.appendChild(ring);setTimeout(()=>ring.remove(),1000);for(let n=0;n<12;n++){const p=document.createElement('i');p.className='reaction-fx '+(kind==='crystal'?'reaction-crystal':'reaction-particle');p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--fx',color);p.style.setProperty('--dx',(-55+Math.random()*110)+'px');p.style.setProperty('--dy',(-65+Math.random()*100)+'px');p.style.setProperty('--rot',(-90+Math.random()*180)+'deg');document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}}
function completeTube(i){const t=S.tubes[i];if(t.length!==CAP||!t.every(x=>x===t[0]))return Promise.resolve(false);const key=t[0],color=E[key].c,tube=document.querySelectorAll('.tube')[i];S.busy=true;tube?.classList.add('completing');return new Promise(res=>{setTimeout(()=>{fxAt(i,color,key==='rose'||key==='citrine'?'crystal':'burst');tube?.classList.add('completion-burst');S.gold+=12;setTimeout(()=>{S.tubes[i]=[];S.busy=false;toast(`${E[key].n}: блок завершено · +12 ◆`);render();res(true)},620)},850)})}
function secretFor(a,b){if(a<0||b<0||a===b)return null;const A=S.tubes[a],B=S.tubes[b];if(!A?.length||!B?.length)return null;const p=[E[A.at(-1)].s,E[B.at(-1)].s];return SECRETS.find(s=>s.pair.every(x=>p.includes(x)))||null}
function secretBanner(sec,artifact){const d=document.createElement('div');d.className='secret-banner';d.innerHTML=`<b>${sec.title}</b>+${sec.bonus} ◆${artifact?` · АРТЕФАКТ: ${artifact}`:''}`;document.body.appendChild(d);setTimeout(()=>d.remove(),1700);if(artifact){const a=document.createElement('div');a.className='artifact-pop';a.textContent='◆';document.body.appendChild(a);setTimeout(()=>a.remove(),1200)}}
function doSecret(a,b,sec){S.busy=true;S.hist.push(clone(S.tubes));const color=sec.fx;animatePour(a,b,color,()=>{S.tubes[a].pop();S.tubes[b].pop();S.moves--;S.gold+=sec.bonus;let artifact=null;if(Math.random()<.28){artifact=sec.artifact;S.artifacts.push({name:artifact,level:S.level,ts:Date.now()});S.nug+=1}S.sel=-1;fxAt(b,sec.fx,sec.kind);document.querySelectorAll('.tube')[b]?.classList.add('secret-reacting');secretBanner(sec,artifact);S.busy=false;save();setTimeout(()=>{render();end()},780)})}
async function tap(i){if(S.busy)return;if(S.sel<0){if(!S.tubes[i].length)return;S.sel=i;$('hint').textContent='Обери підсвічену колбу';render();return}if(S.sel===i){S.sel=-1;render();return}const a=S.sel,n=legal(S.tubes,a,i),sec=secretFor(a,i);if(!n&&sec){doSecret(a,i,sec);return}if(!n){document.querySelectorAll('.tube')[i]?.classList.add('shake');setTimeout(()=>render(),320);S.sel=-1;return}const next=clone(S.tubes);for(let k=0;k<n;k++)next[i].push(next[a].pop());S.busy=true;S.hist.push(clone(S.tubes));const color=E[S.tubes[a].at(-1)].c;animatePour(a,i,color,async()=>{S.tubes=next;S.moves--;S.sel=-1;S.busy=false;render();await completeTube(i);end()})}
function end(){if(cleared()){const rw=40+S.level*5,xp=20+S.level*3;S.gold+=rw;S.xp+=xp;save();$('winReward').textContent=`+${rw} ◆`;$('winXp').textContent=`+${xp} XP`;$('win').classList.add('show')}else if(S.moves<=0)$('lose').classList.add('show')}
function bestHint(){for(let a=0;a<S.tubes.length;a++)for(let b=0;b<S.tubes.length;b++)if(legal(S.tubes,a,b))return[a,b];return null}
$('undo').onclick=()=>{if(S.busy)return;if(S.undo<=0)return toast('Скасування закінчились');if(!S.hist.length)return toast('Немає ходу для скасування');S.tubes=S.hist.pop();S.undo--;S.moves++;S.sel=-1;render()};
$('shuffle').onclick=()=>{if(S.busy)return;if(S.shuffle<=0)return toast('Перемішування закінчились');S.shuffle--;S.tubes=build(Date.now()%997);S.hist=[];S.moves=Math.max(S.moves,S.par+10);S.sel=-1;render();toast('Новий розклад')};
$('addTube').onclick=()=>{if(S.busy)return;if(S.extra)return toast('Додаткова колба вже встановлена');S.tubes.push([]);S.extra=true;render();toast('Додано порожню колбу')};
$('hintBtn').onclick=()=>{if(S.busy)return;if(S.hints<=0)return toast('Підказки закінчились');const h=bestHint();if(!h)return toast('Спробуй секретну комбінацію або перемішай');S.hints--;S.sel=h[0];render();toast(`Підказка: ${h[0]+1} → ${h[1]+1}`)};
$('station').onclick=()=>{if(S.busy)return;const r=reaction(),need=r.need[S.reactionStep];if(S.sel<0)return toast(`Обери зразок ${need}`);const tube=S.tubes[S.sel],sym=tube.length?E[tube.at(-1)].s:null;if(sym!==need){S.sel=-1;render();return toast(`Для ${r.formula} потрібен ${need}`)}S.reactionStep++;S.sel=-1;if(S.reactionStep>=r.need.length){S.reactionStep=0;S.reactionIndex++;S.gold+=15;save();toast(`Синтезовано ${r.formula} · +15 ◆`)}else toast(`${sym} додано до синтезу`);render()};
$('next').onclick=()=>{$('win').classList.remove('show');start(S.level+1)};$('more').onclick=()=>{$('lose').classList.remove('show');S.moves+=3;render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level)};$('sound').onclick=()=>{S.muted=!S.muted;localStorage.cl9_muted=S.muted?'1':'0';$('sound').textContent=S.muted?'🔇':'🔊'};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');start(S.level);
})();