(()=>{
'use strict';
const CAP=4, CAMPAIGN=118;
const SYMBOLS=['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'];
const NAMES=['Гідроген','Гелій','Літій','Берилій','Бор','Карбон','Нітроген','Оксиген','Флуор','Неон','Натрій','Магній','Алюміній','Силіцій','Фосфор','Сульфур','Хлор','Аргон','Калій','Кальцій','Скандій','Титан','Ванадій','Хром','Манган','Ферум','Кобальт','Нікель','Купрум','Цинк','Галій','Германій','Арсен','Селен','Бром','Криптон','Рубідій','Стронцій','Ітрій','Цирконій','Ніобій','Молібден','Технецій','Рутеній','Родій','Паладій','Аргентум','Кадмій','Індій','Станум','Стибій','Телур','Йод','Ксенон','Цезій','Барій','Лантан','Церій','Празеодим','Неодим','Прометій','Самарій','Європій','Гадоліній','Тербій','Диспрозій','Гольмій','Ербій','Тулій','Ітербій','Лютецій','Гафній','Тантал','Вольфрам','Реній','Осмій','Іридій','Платина','Аурум','Меркурій','Талій','Плюмбум','Бісмут','Полоній','Астат','Радон','Францій','Радій','Актиній','Торій','Протактиній','Уран','Нептуній','Плутоній','Америцій','Кюрій','Берклій','Каліфорній','Ейнштейній','Фермій','Менделєвій','Нобелій','Лоуренсій','Резерфордій','Дубній','Сіборгій','Борій','Гасій','Майтнерій','Дармштадтій','Рентгеній','Коперницій','Ніхоній','Флеровій','Московій','Ліверморій','Теннессин','Оганесон'];
const DISCOVERY=['Na','Cl','Fe','O','C','H','Au',...SYMBOLS.filter(s=>!['Na','Cl','Fe','O','C','H','Au'].includes(s))];
const zOf=s=>SYMBOLS.indexOf(s)+1;
const SETS={alkali:new Set(['Li','Na','K','Rb','Cs','Fr']),alkaline:new Set(['Be','Mg','Ca','Sr','Ba','Ra']),halogen:new Set(['F','Cl','Br','I','At','Ts']),noble:new Set(['He','Ne','Ar','Kr','Xe','Rn','Og']),metalloid:new Set(['B','Si','Ge','As','Sb','Te']),nonmetal:new Set(['H','C','N','O','P','S','Se']),lanthanide:new Set(SYMBOLS.slice(56,71)),actinide:new Set(SYMBOLS.slice(88,103))};
function category(s){const z=zOf(s);if(SETS.alkali.has(s))return['Лужний метал','alkali'];if(SETS.alkaline.has(s))return['Лужноземельний метал','alkaline'];if(SETS.halogen.has(s))return['Галоген','halogen'];if(SETS.noble.has(s))return['Благородний газ','noble'];if(SETS.metalloid.has(s))return['Металоїд','metalloid'];if(SETS.nonmetal.has(s))return['Неметал','nonmetal'];if(SETS.lanthanide.has(s))return['Лантаноїд','lanthanide'];if(SETS.actinide.has(s))return['Актиноїд','actinide'];if((z>=21&&z<=30)||(z>=39&&z<=48)||(z>=72&&z<=80)||(z>=104&&z<=112))return['Перехідний метал','transition'];return['Метал','metal']}
function rarity(s){const z=zOf(s);if(z>=104||['Au','Pt','U','Pu'].includes(s))return['Легендарний','legendary'];if(z>=72||SETS.actinide.has(s)||SETS.lanthanide.has(s))return['Епічний','epic'];if(z>=31||SETS.noble.has(s))return['Рідкісний','rare'];return['Звичайний','common']}
function hueFor(s){const z=zOf(s);return ((z*41)+17)%360}
const E={};SYMBOLS.forEach((s,i)=>{const [cat,catKey]=category(s),[rar,rarKey]=rarity(s),h=hueFor(s);E[s]={s,z:i+1,n:NAMES[i],cat,catKey,rar,rarKey,c:`hsl(${h} 78% 54%)`,c2:`hsl(${h} 88% 70%)`}});
Object.assign(E,{Na:{...E.Na,c:'#ff535d',c2:'#ff8c94'},Cl:{...E.Cl,c:'#35e68b',c2:'#79f2b1'},Fe:{...E.Fe,c:'#ffb43f',c2:'#ffd071'},O:{...E.O,c:'#20b9ff',c2:'#64d4ff'},C:{...E.C,c:'#9c57f6',c2:'#c18cff'},H:{...E.H,c:'#4fe0e7',c2:'#92f0f3'},Au:{...E.Au,c:'#ffd84d',c2:'#fff08e'}});
const RANKS=[{x:0,n:'Учень лабораторії'},{x:180,n:'Лаборант'},{x:500,n:'Хімік'},{x:1200,n:'Дослідник'},{x:2800,n:'Майстер синтезу'},{x:6000,n:'Архітектор матерії'}];
const REACTIONS=[{id:'nacl',formula:'NaCl',name:'Хлорид натрію',need:['Na','Cl']},{id:'h2o',formula:'H₂O',name:'Вода',need:['H','O']},{id:'co2',formula:'CO₂',name:'Діоксид карбону',need:['C','O']},{id:'mgo',formula:'MgO',name:'Оксид магнію',need:['Mg','O']},{id:'cao',formula:'CaO',name:'Оксид кальцію',need:['Ca','O']},{id:'al2o3',formula:'Al₂O₃',name:'Оксид алюмінію',need:['Al','O']},{id:'sio2',formula:'SiO₂',name:'Діоксид силіцію',need:['Si','O']},{id:'fe2o3',formula:'Fe₂O₃',name:'Оксид феруму',need:['Fe','O']},{id:'cuo',formula:'CuO',name:'Оксид купруму',need:['Cu','O']},{id:'zno',formula:'ZnO',name:'Оксид цинку',need:['Zn','O']},{id:'kcl',formula:'KCl',name:'Хлорид калію',need:['K','Cl']},{id:'mgcl2',formula:'MgCl₂',name:'Хлорид магнію',need:['Mg','Cl']},{id:'cacl2',formula:'CaCl₂',name:'Хлорид кальцію',need:['Ca','Cl']},{id:'agcl',formula:'AgCl',name:'Хлорид аргентуму',need:['Ag','Cl']},{id:'nh3',formula:'NH₃',name:'Амоніак',need:['N','H']},{id:'so2',formula:'SO₂',name:'Діоксид сульфуру',need:['S','O']},{id:'no2',formula:'NO₂',name:'Діоксид нітрогену',need:['N','O']},{id:'lif',formula:'LiF',name:'Фторид літію',need:['Li','F']},{id:'caf2',formula:'CaF₂',name:'Фторид кальцію',need:['Ca','F']},{id:'sicl4',formula:'SiCl₄',name:'Тетрахлорид силіцію',need:['Si','Cl']}];
const SECRETS=[{id:'nacl_secret',pair:['Na','Cl'],kind:'crystal',title:'СЕКРЕТ: КРИСТАЛІЗАЦІЯ',bonus:28,fx:'#b7fff0',artifact:'Кристал солі'},{id:'ho_secret',pair:['H','O'],kind:'flash',title:'СЕКРЕТ: ЕНЕРГЕТИЧНИЙ СПАЛАХ',bonus:35,fx:'#7ee9ff',artifact:'Плазмовий уламок'},{id:'feo_secret',pair:['Fe','O'],kind:'crystal',title:'СЕКРЕТ: ОКСИДНИЙ КРИСТАЛ',bonus:32,fx:'#ff9f42',artifact:'Оксидний фрагмент'},{id:'co_secret',pair:['C','O'],kind:'burst',title:'СЕКРЕТ: ВУГЛЕЦЕВИЙ ІМПУЛЬС',bonus:30,fx:'#b86cff',artifact:'Темний каталізатор'}];
const HAZARDS=[{id:'tox',pair:['Na','O'],title:'НЕСТАБІЛЬНА ТОКСИЧНА ФАЗА',penalty:18,fx:'#9dff5b',status:'☠ токсична фаза',contam:2,jackpot:42,artifact:'Стабілізований токсик-фрагмент'},{id:'cor',pair:['Fe','C'],title:'КОРОЗІЙНИЙ КОМПЛЕКС',penalty:14,fx:'#ff7a3d',status:'⚠ корозійний продукт',contam:2,jackpot:38,artifact:'Корозійний каталізатор'},{id:'iso',pair:['Au','O'],title:'АНОМАЛЬНИЙ ІЗОТОП',penalty:24,fx:'#d8ff38',status:'☢ нестабільний ізотоп',contam:3,jackpot:55,artifact:'Ізотопний уламок'}];
const LABS=[['Молекулярна лабораторія','molecular'],['Реактивна камера','reactive'],['Кристалічний сектор','crystal'],['Ізотопний модуль','isotope'],['Фронтир 118','frontier']];
const LEVEL_TYPES=[['Калібрування','calibration'],['Відкриття','discovery'],['Каталіз','catalyst'],['Нестабільність','volatile'],['BOSS-дослід','boss']];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
let old25={};try{old25=JSON.parse(localStorage.getItem('cl25_state')||'{}')}catch{}let old24={};try{old24=JSON.parse(localStorage.getItem('cl24_state')||'{}')}catch{}let saved={};try{saved=JSON.parse(localStorage.getItem('cl27_state')||'{}')}catch{}
let discovered=new Set(Array.isArray(saved.discovered)?saved.discovered:(Array.isArray(old25.discovered)?old25.discovered:[]));if(!discovered.size)['Na','Cl','Fe'].forEach(s=>discovered.add(s));
const S={level:+saved.level||+old25.level||+old24.level||1,gold:+saved.gold||+old25.gold||+old24.gold||0,nug:+saved.nug||+old25.nug||+old24.nug||0,xp:+saved.xp||+old25.xp||+old24.xp||0,tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:saved.muted??old25.muted??old24.muted??false,par:0,solution:[],reactionIndex:+saved.reactionIndex||+old25.reactionIndex||0,artifacts:Array.isArray(saved.artifacts)?saved.artifacts:(Array.isArray(old25.artifacts)?old25.artifacts:[]),hazards:+saved.hazards||+old25.hazards||0,contam:{},usedEvents:new Set(),journal:Array.isArray(saved.journal)?saved.journal:(Array.isArray(old25.journal)?old25.journal:[]),recipes:new Set(Array.isArray(saved.recipes)?saved.recipes:[]),score:+saved.score||0};
function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function labInfo(){const i=Math.min(4,Math.floor((Math.min(S.level,118)-1)/24));return LABS[i]}function typeInfo(){return LEVEL_TYPES[(S.level-1)%5]}
function stateDetail(){return{level:S.level,discovered:[...discovered],artifacts:S.artifacts,journal:S.journal,recipes:[...S.recipes],score:S.score,lab:labInfo()[0],levelType:typeInfo()[0]}}
function persist(){localStorage.setItem('cl27_state',JSON.stringify({level:S.level,gold:S.gold,nug:S.nug,xp:S.xp,muted:S.muted,reactionIndex:S.reactionIndex,artifacts:S.artifacts,hazards:S.hazards,discovered:[...discovered],journal:S.journal.slice(-160),recipes:[...S.recipes],score:S.score}));localStorage.setItem('cl12_discovered_elements',JSON.stringify([...discovered]));if($('gold'))$('gold').textContent=S.gold;if($('nugget'))$('nugget').textContent=S.nug;window.dispatchEvent(new CustomEvent('chemlab:state',{detail:stateDetail()}))}
function targetDiscoveries(level){return Math.min(118,3+Math.floor(Math.max(0,level-1)/2)*2)}
function unlockForLevel(){const target=targetDiscoveries(S.level),fresh=[];for(let i=0;i<target;i++){const s=DISCOVERY[i];if(s&&!discovered.has(s)){discovered.add(s);fresh.push(s);S.journal.push({type:'element',symbol:s,name:E[s].n,level:S.level,ts:Date.now()})}}persist();if(fresh.length)setTimeout(()=>revealElements(fresh),350)}
function revealElements(list){const s=list[0],e=E[s];const ov=document.createElement('div');ov.className='discovery-reveal';ov.innerHTML=`<div class="discovery-card ${e.rarKey}"><small>НОВЕ ВІДКРИТТЯ · Z=${e.z}</small><strong>${e.s}</strong><h3>${e.n}</h3><p>${e.cat} · ${e.rar}</p><div class="discovery-count">${discovered.size} / 118</div></div>`;document.body.appendChild(ov);requestAnimationFrame(()=>ov.classList.add('show'));setTimeout(()=>{ov.classList.remove('show');setTimeout(()=>ov.remove(),400);if(list.length>1)revealElements(list.slice(1))},1700)}
function applyTheme(){const [lab,labKey]=labInfo(),[type,typeKey]=typeInfo();document.body.dataset.lab=labKey;document.body.dataset.levelType=typeKey;let strip=document.getElementById('missionStrip');if(!strip){strip=document.createElement('div');strip.id='missionStrip';strip.className='mission-strip';document.querySelector('.status')?.after(strip)}strip.innerHTML=`<span>${lab}</span><b>${type}</b>${typeKey==='boss'?'<i><em></em></i>':''}`}
function artifactNames(){return new Set(S.artifacts.map(a=>a.name))}function passiveBonuses(){const a=artifactNames();return{moves:a.has('Плазмовий уламок')?2:0,hints:a.has('Кристал солі')?1:0,undo:a.has('Оксидний фрагмент')?1:0,reward:a.has('Темний каталізатор')?.12:0,nug:a.has('Ізотопний уламок')?1:0}}
function pool(){const d=DISCOVERY.filter(s=>discovered.has(s)),need=Math.min(typeInfo()[1]==='boss'?5:(S.level<10?3:4),d.length);if(d.length<=need)return d.slice();const out=[],start=(S.level*7)%d.length,step=5;for(let k=0;out.length<need&&k<d.length*2;k++){const s=d[(start+k*step)%d.length];if(!out.includes(s))out.push(s)}for(const s of d)if(out.length<need&&!out.includes(s))out.push(s);return out.slice(0,need)}
function seeded(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}function shuffleArr(a,r){for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function build(seedOffset=0){const colors=pool(),r=seeded(S.level*9973+seedOffset*131071+71),chunk=(S.level>=8&&typeInfo()[1]!=='discovery')?2:1;const sources=shuffleArr(colors.slice(),r).map(c=>Array(CAP-chunk).fill(c));const groups=shuffleArr(colors.map(c=>({c,n:chunk})),r);const bufferCount=Math.max(1,Math.ceil(colors.length*chunk/CAP)),buffers=Array.from({length:bufferCount},()=>[]),placements=[];let bi=0;for(const g of groups){let guard=0;while(buffers[bi].length+g.n>CAP&&guard++<bufferCount+2)bi=(bi+1)%bufferCount;const idx=bi;for(let n=0;n<g.n;n++)buffers[idx].push(g.c);placements.push({buffer:idx,color:g.c,n:g.n});bi=(bi+1)%bufferCount}const T=[...sources,...buffers,[]],sourceIndex=new Map();sources.forEach((t,i)=>sourceIndex.set(t[0],i));const solution=[];for(let b=0;b<buffers.length;b++){const stack=placements.filter(p=>p.buffer===b);for(let k=stack.length-1;k>=0;k--){const p=stack[k];solution.push([sources.length+b,sourceIndex.get(p.color),p.n])}}S.solution=solution;S.par=solution.length;return T}
function topRun(t){if(!t.length)return 0;const x=t[t.length-1];let n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}function isLocked(i){return(S.contam[i]||0)>0}function legal(T,a,b){const A=T[a],B=T[b];if(a===b||isLocked(a)||isLocked(b)||!A?.length||!B||B.length>=CAP)return 0;const x=A[A.length-1];if(B.length&&B[B.length-1]!==x)return 0;return Math.min(topRun(A),CAP-B.length)}function apply(T,a,b,n){for(let i=0;i<n;i++)T[b].push(T[a].pop())}function eventPair(a,b){if(a<0||b<0||a===b)return null;const A=S.tubes[a],B=S.tubes[b];if(!A?.length||!B?.length)return null;return[A[A.length-1],B[B.length-1]]}function eventFor(list,a,b){const p=eventPair(a,b);if(!p)return null;return list.find(e=>e.pair.every(x=>p.includes(x))&&!S.usedEvents.has(e.id))||null}function fullUniform(t){return t.length===CAP&&t.every(x=>x===t[0])}function cleared(){return S.tubes.every(t=>!t.length)}function decrementContam(){for(const k of Object.keys(S.contam)){S.contam[k]--;if(S.contam[k]<=0)delete S.contam[k]}}
function snapshot(){return{tubes:clone(S.tubes),moves:S.moves,contam:{...S.contam},gold:S.gold,nug:S.nug,score:S.score,artifacts:clone(S.artifacts),used:[...S.usedEvents]}}function restore(x){S.tubes=x.tubes;S.moves=x.moves;S.contam=x.contam;S.gold=x.gold;S.nug=x.nug;S.score=x.score;S.artifacts=x.artifacts;S.usedEvents=new Set(x.used)}
function rankUI(){let r=RANKS[0];for(const x of RANKS)if(S.xp>=x.x)r=x;const i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function availableReactions(){return REACTIONS.filter(r=>r.need.every(x=>discovered.has(x)))}function stationUI(){const a=availableReactions(),box=$('recipe');if(!box)return;if(!a.length){box.innerHTML='<div class="slot product">???</div>';$('stationText').textContent='Відкривай елементи, щоб знаходити нові сполуки';return}S.reactionIndex%=a.length;const r=a[S.reactionIndex],known=S.recipes.has(r.id);box.innerHTML='';r.need.forEach((sym,i)=>{if(i){const plus=document.createElement('span');plus.className='arrow';plus.textContent='+';box.appendChild(plus)}const d=document.createElement('div');d.className='slot';d.textContent=known?sym:'?';box.appendChild(d)});const ar=document.createElement('span');ar.className='arrow';ar.textContent='→';box.appendChild(ar);const p=document.createElement('div');p.className='slot product';p.textContent=known?r.formula:'???';box.appendChild(p);$('stationText').innerHTML=known?`${r.need.join(' + ')} → ${r.formula}<br><span style="opacity:.72">${r.name} · рецепт у журналі</span>`:`Невідомий рецепт · торкнись станції, щоб дослідити`}
function render(){applyTheme();const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';wrap.dataset.index=i;const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(isLocked(i)){el.classList.add('contaminated');el.dataset.contam=S.contam[i]}else if(S.sel>=0&&i!==S.sel){const haz=eventFor(HAZARDS,S.sel,i),sec=eventFor(SECRETS,S.sel,i);if(haz)el.classList.add('risky');else el.classList.add(legal(S.tubes,S.sel,i)||sec?'valid':'dim')}const inn=document.createElement('div');inn.className='tube-inner';tube.forEach((s,li)=>{const e=E[s],d=document.createElement('div');d.className=`layer element-${e.catKey} rarity-${e.rarKey}`;d.dataset.slot=li;d.dataset.symbol=s;d.dataset.category=e.catKey;d.style.bottom=`calc(5px + ${li} * ((100% - 12px)/4))`;d.style.background=`linear-gradient(180deg,${e.c2},${e.c})`;d.style.setProperty('--glow',e.c);const label=document.createElement('span');label.className='fluid-symbol';label.textContent=s;d.appendChild(label);inn.appendChild(d)});el.appendChild(inn);wrap.appendChild(el);bindTube(wrap,i);board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;const active=[...new Set(S.tubes.flat())];$('levelSub').textContent=`${discovered.size}/118 · ${active.join(' · ')}`;$('footerLevel').textContent=`Таблиця ${discovered.size} / 118 ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();stationUI();persist();requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('chemlab:render')))}
function bindTube(wrap,i){let down=null;wrap.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;down={x:e.clientX,y:e.clientY,id:e.pointerId};try{wrap.setPointerCapture(e.pointerId)}catch{}},{passive:true});wrap.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId)return;const dist=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(dist<=10){e.preventDefault();tap(i)}});wrap.addEventListener('pointercancel',()=>down=null)}
function start(level,seed=0){S.level=Math.max(1,Math.min(999,level));unlockForLevel();const p=passiveBonuses();S.tubes=build(seed);S.sel=-1;S.hist=[];S.undo=3+p.undo;S.shuffle=3;S.hints=3+p.hints;S.extra=false;S.busy=false;S.contam={};S.usedEvents=new Set();const type=typeInfo()[1],pressure=type==='boss'?2:type==='volatile'?1:0;S.moves=Math.max(S.par+6+p.moves-pressure,14);render()}
function makeStream(x1,y1,x2,y2,color,duration=1050){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','liquid-stream-svg');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','liquid-stream-path');p.style.setProperty('--pourColor',color);p.setAttribute('d',`M ${x1} ${y1} C ${x1} ${y1+42}, ${x2} ${y2-34}, ${x2} ${y2}`);svg.appendChild(p);document.body.appendChild(svg);let len=180;try{len=p.getTotalLength()}catch{}p.style.strokeDasharray=len;p.style.strokeDashoffset=len;p.animate([{strokeDashoffset:len,opacity:0},{strokeDashoffset:0,opacity:1,offset:.2},{strokeDashoffset:0,opacity:1,offset:.8},{strokeDashoffset:-len*.2,opacity:0}],{duration,easing:'ease-in-out'});setTimeout(()=>svg.remove(),duration+120)}
function animatePour(a,b,n,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst||!src.animate){done();return}const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=B.left>A.left?1:-1,g=src.cloneNode(true);g.className='tube pour-ghost';Object.assign(g.style,{left:A.left+'px',top:A.top+'px',width:A.width+'px',height:A.height+'px'});document.body.appendChild(g);src.style.opacity='.18';const dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*10,dy=(B.top-A.top)-A.height*.42,tilt=dir*62,duration=2050;const an=g.animate([{transform:'translate3d(0,0,0) rotate(0)',offset:0},{transform:`translate3d(${dx*.4}px,${dy*.34}px,0) rotate(${tilt*.09}deg)`,offset:.22},{transform:`translate3d(${dx}px,${dy}px,0) rotate(${tilt}deg)`,offset:.44},{transform:`translate3d(${dx}px,${dy+2}px,0) rotate(${tilt}deg)`,offset:.77},{transform:`translate3d(${dx*.5}px,${dy*.42}px,0) rotate(${tilt*.16}deg)`,offset:.91},{transform:'translate3d(0,0,0) rotate(0)',offset:1}],{duration,easing:'cubic-bezier(.2,.68,.18,1)',fill:'forwards'});setTimeout(()=>{const x=B.left+B.width/2,y=B.top+8;makeStream(x-dir*17,y-70,x,y,color,900);dst.classList.add('receiving');setTimeout(()=>dst.classList.remove('receiving'),1100)},760);Promise.resolve(an.finished).catch(()=>{}).finally(()=>{src.style.opacity='';g.remove();done()})}
function fxAt(i,color,kind='burst'){const tube=document.querySelectorAll('.tube')[i];if(!tube)return;const r=tube.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height*.46;const ring=document.createElement('i');ring.className='reaction-fx reaction-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--fx',color);document.body.appendChild(ring);setTimeout(()=>ring.remove(),1000);for(let n=0;n<14;n++){const p=document.createElement('i');p.className='reaction-fx '+(kind==='crystal'?'reaction-crystal':'reaction-particle');p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--fx',color);p.style.setProperty('--x',`${Math.cos(n/14*Math.PI*2)*(28+Math.random()*42)}px`);p.style.setProperty('--y',`${Math.sin(n/14*Math.PI*2)*(28+Math.random()*42)}px`);document.body.appendChild(p);setTimeout(()=>p.remove(),1200)}}
function addArtifact(name){if(S.artifacts.some(a=>a.name===name))return false;S.artifacts.push({name,level:S.level,ts:Date.now()});S.journal.push({type:'artifact',name,level:S.level,ts:Date.now()});return true}
function elementCompletionBonus(sym){const e=E[sym];let gold=10,nug=0,label=e.cat;if(e.catKey==='noble'){S.moves+=1;label='Благородний газ · +1 хід'}else if(e.catKey==='transition')gold+=4;else if(e.catKey==='halogen')gold+=3;else if(e.catKey==='lanthanide'||e.catKey==='actinide'){nug=1;label=`${e.cat} · +1 рідкісний кристал`}else if(e.rarKey==='legendary'){gold+=8;nug=1}S.gold+=gold;S.nug+=nug;S.score+=gold*5;return label}
function completeTube(i){return new Promise(resolve=>{const t=S.tubes[i];if(!fullUniform(t)){resolve();return}const sym=t[0],el=document.querySelectorAll('.tube')[i],e=E[sym];S.busy=true;el?.classList.add('completing');setTimeout(()=>{fxAt(i,e.c,e.catKey==='metal'||e.catKey==='transition'?'crystal':'burst');const label=elementCompletionBonus(sym);setTimeout(()=>{S.tubes[i]=[];S.busy=false;toast(`${sym} очищено · ${label}`);render();resolve()},560)},620)})}
function specialEvent(a,b,e,hazard=false){S.usedEvents.add(e.id);S.moves=Math.max(0,S.moves-1);S.score+=hazard?5:e.bonus*4;if(hazard){S.hazards++;const jackpot=Math.random()<.22;if(jackpot){S.gold+=e.jackpot;S.nug+=1;addArtifact(e.artifact);toast(`РИЗИК ВИПРАВДАНО · +${e.jackpot}`)}else{S.gold=Math.max(0,S.gold-e.penalty);S.contam[b]=e.contam;toast(`${e.status} · пробірка заблокована на ${e.contam} ходи`)}}else{S.gold+=e.bonus;if(Math.random()<.32){addArtifact(e.artifact);S.nug+=1;toast(`${e.title} · знайдено артефакт`)}else toast(`${e.title} · +${e.bonus}`)}fxAt(b,e.fx,e.kind||'burst');decrementContam();render();checkEnd()}
function tap(i){if(S.busy)return;if(isLocked(i)){toast(`Контамінація: ще ${S.contam[i]} ходи`);return}const t=S.tubes[i];if(S.sel<0){if(t.length){S.sel=i;render()}return}if(i===S.sel){S.sel=-1;render();return}const a=S.sel,haz=eventFor(HAZARDS,a,i),sec=eventFor(SECRETS,a,i),n=legal(S.tubes,a,i);if(!n&&!(haz||sec)){if(t.length){S.sel=i;render()}else{S.sel=-1;toast('Цей перенос неможливий');render()}return}S.hist.push(snapshot());if(S.hist.length>12)S.hist.shift();S.sel=-1;if(!n&&(haz||sec)){specialEvent(a,i,haz||sec,!!haz);return}const sym=S.tubes[a][S.tubes[a].length-1],color=E[sym].c;S.busy=true;animatePour(a,i,n,color,async()=>{apply(S.tubes,a,i,n);S.moves--;decrementContam();S.busy=false;render();await completeTube(i);checkEnd()})}
function checkEnd(){if(cleared()){const p=passiveBonuses(),boss=typeInfo()[1]==='boss',reward=Math.round((45+S.level*3)*(1+p.reward)+(boss?35:0)),xp=24+Math.min(S.level,118)*2+(boss?20:0);S.gold+=reward;S.nug+=p.nug;S.xp+=xp;S.score+=reward*10;$('winReward').textContent=`+${reward} ◉${p.nug?' · +'+p.nug+' ◇':''}`;$('winXp').textContent=`+${xp} XP · SCORE ${S.score}`;$('win').classList.add('show');persist();return}if(S.moves<=0)$('lose').classList.add('show')}
function hint(){if(S.busy||S.hints<=0){toast('Підказок немає');return}for(const [a,b] of S.solution){if(S.tubes[a]?.length&&legal(S.tubes,a,b)){S.hints--;toast(`Підказка: ${a+1} → ${b+1}`);render();setTimeout(()=>{document.querySelectorAll('.tube')[a]?.classList.add('hint-source');document.querySelectorAll('.tube')[b]?.classList.add('hint-target')},20);setTimeout(()=>render(),1300);return}}for(let a=0;a<S.tubes.length;a++)for(let b=0;b<S.tubes.length;b++)if(legal(S.tubes,a,b)){S.hints--;toast(`Спробуй ${a+1} → ${b+1}`);render();return}toast('Немає доступного ходу')}
function synthesize(){const a=availableReactions();if(!a.length){toast('Ще немає доступних рецептів');return}S.reactionIndex%=a.length;const r=a[S.reactionIndex];if(!S.recipes.has(r.id)){S.recipes.add(r.id);S.journal.push({type:'reaction',formula:r.formula,name:r.name,level:S.level,ts:Date.now()});S.gold+=12;S.score+=120;toast(`Відкрито рецепт ${r.formula} · +12`)}else{S.reactionIndex=(S.reactionIndex+1)%a.length;toast('Наступний рецепт')}render()}
$('undo').onclick=()=>{if(S.busy||!S.hist.length||S.undo<=0){toast('Немає скасувань');return}restore(S.hist.pop());S.undo--;S.sel=-1;render()};$('shuffle').onclick=()=>{if(S.busy||S.shuffle<=0){toast('Перемішувань немає');return}S.shuffle--;S.tubes=build(Date.now()%997);S.moves=Math.max(S.par+6+passiveBonuses().moves,14);S.hist=[];S.sel=-1;S.contam={};render();toast('Новий гарантовано прохідний розклад')};$('addTube').onclick=()=>{if(S.busy||S.extra){toast('Додаткову пробірку вже використано');return}S.tubes.push([]);S.extra=true;render();toast('Додано резервну пробірку')};$('hintBtn').onclick=hint;$('more').onclick=()=>{S.moves+=3;$('lose').classList.remove('show');render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level,Date.now()%10000)};$('next').onclick=()=>{$('win').classList.remove('show');start(S.level+1)};$('sound').onclick=()=>{S.muted=!S.muted;$('sound').textContent=S.muted?'🔇':'🔊';persist()};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');$('station').addEventListener('click',synthesize);
window.ChemLab27={getState:()=>stateDetail(),element:s=>E[s],start};start(S.level);
})();