(()=>{
'use strict';
const CAP=4, CAMPAIGN=118;
const SYMBOLS=['H','He','Li','Be','B','C','N','O','F','Ne','Na','Mg','Al','Si','P','S','Cl','Ar','K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr','Rb','Sr','Y','Zr','Nb','Mo','Tc','Ru','Rh','Pd','Ag','Cd','In','Sn','Sb','Te','I','Xe','Cs','Ba','La','Ce','Pr','Nd','Pm','Sm','Eu','Gd','Tb','Dy','Ho','Er','Tm','Yb','Lu','Hf','Ta','W','Re','Os','Ir','Pt','Au','Hg','Tl','Pb','Bi','Po','At','Rn','Fr','Ra','Ac','Th','Pa','U','Np','Pu','Am','Cm','Bk','Cf','Es','Fm','Md','No','Lr','Rf','Db','Sg','Bh','Hs','Mt','Ds','Rg','Cn','Nh','Fl','Mc','Lv','Ts','Og'];
const DISCOVERY=['Na','Cl','Fe','O','C','H','Au',...SYMBOLS.filter(s=>!['Na','Cl','Fe','O','C','H','Au'].includes(s))];
const NAMES={H:'Гідроген',He:'Гелій',Li:'Літій',Be:'Берилій',B:'Бор',C:'Карбон',N:'Нітроген',O:'Оксиген',F:'Флуор',Ne:'Неон',Na:'Натрій',Mg:'Магній',Al:'Алюміній',Si:'Силіцій',P:'Фосфор',S:'Сульфур',Cl:'Хлор',Ar:'Аргон',K:'Калій',Ca:'Кальцій',Fe:'Ферум',Cu:'Купрум',Zn:'Цинк',Ag:'Аргентум',Au:'Аурум',Hg:'Меркурій',Pb:'Плюмбум',U:'Уран',Pu:'Плутоній',Og:'Оганесон'};
const colorFor=(s,i=SYMBOLS.indexOf(s))=>{const hue=((i<0?0:i)*47+12)%360;return `hsl(${hue} 78% 57%)`};
const lightFor=(s,i=SYMBOLS.indexOf(s))=>{const hue=((i<0?0:i)*47+12)%360;return `hsl(${hue} 86% 70%)`};
const E={}; SYMBOLS.forEach((s,i)=>E[s]={s,n:NAMES[s]||s,c:colorFor(s,i),c2:lightFor(s,i)});
Object.assign(E,{Na:{s:'Na',n:'Натрій',c:'#ff535d',c2:'#ff8c94'},Cl:{s:'Cl',n:'Хлор',c:'#35e68b',c2:'#79f2b1'},Fe:{s:'Fe',n:'Ферум',c:'#ffb43f',c2:'#ffd071'},O:{s:'O',n:'Оксиген',c:'#20b9ff',c2:'#64d4ff'},C:{s:'C',n:'Карбон',c:'#9c57f6',c2:'#c18cff'},H:{s:'H',n:'Гідроген',c:'#4fe0e7',c2:'#92f0f3'},Au:{s:'Au',n:'Аурум',c:'#ffd84d',c2:'#fff08e'}});
const RANKS=[{x:0,n:'Учень лабораторії'},{x:180,n:'Лаборант'},{x:500,n:'Хімік'},{x:1200,n:'Дослідник'},{x:2800,n:'Майстер синтезу'},{x:6000,n:'Архітектор матерії'}];
const REACTIONS=[{formula:'NaCl',name:'Хлорид натрію',eq:'Na + Cl → NaCl',need:['Na','Cl']},{formula:'H₂O',name:'Вода',eq:'H + O → H₂O',need:['H','O']},{formula:'Fe₂O₃',name:'Оксид феруму',eq:'Fe + O → Fe₂O₃',need:['Fe','O']},{formula:'CO₂',name:'Діоксид карбону',eq:'C + O → CO₂',need:['C','O']}];
const SECRETS=[{id:'nacl',pair:['Na','Cl'],kind:'crystal',title:'СЕКРЕТ: КРИСТАЛІЗАЦІЯ',bonus:28,fx:'#b7fff0',artifact:'Кристал солі'},{id:'ho',pair:['H','O'],kind:'flash',title:'СЕКРЕТ: ЕНЕРГЕТИЧНИЙ СПАЛАХ',bonus:35,fx:'#7ee9ff',artifact:'Плазмовий уламок'},{id:'feo',pair:['Fe','O'],kind:'crystal',title:'СЕКРЕТ: ОКСИДНИЙ КРИСТАЛ',bonus:32,fx:'#ff9f42',artifact:'Оксидний фрагмент'},{id:'co',pair:['C','O'],kind:'burst',title:'СЕКРЕТ: ВУГЛЕЦЕВИЙ ІМПУЛЬС',bonus:30,fx:'#b86cff',artifact:'Темний каталізатор'}];
// Fictional gameplay hazards only. No real-world preparation methods, quantities, doses, or conditions.
const HAZARDS=[{id:'tox',pair:['Na','O'],title:'НЕСТАБІЛЬНА ТОКСИЧНА ФАЗА',penalty:18,fx:'#9dff5b',status:'☠ токсична фаза',contam:2,jackpot:42,artifact:'Стабілізований токсик-фрагмент'},{id:'cor',pair:['Fe','C'],title:'КОРОЗІЙНИЙ КОМПЛЕКС',penalty:14,fx:'#ff7a3d',status:'⚠ корозійний продукт',contam:2,jackpot:38,artifact:'Корозійний каталізатор'},{id:'iso',pair:['Au','O'],title:'АНОМАЛЬНИЙ ІЗОТОП',penalty:24,fx:'#d8ff38',status:'☢ нестабільний ізотоп',contam:3,jackpot:55,artifact:'Ізотопний уламок'}];
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
let legacy={};try{legacy=JSON.parse(localStorage.getItem('cl24_state')||'{}')}catch{}
let saved={};try{saved=JSON.parse(localStorage.getItem('cl25_state')||'{}')}catch{}
let discovered=new Set(Array.isArray(saved.discovered)?saved.discovered:[]);if(!discovered.size){['Na','Cl','Fe'].forEach(s=>discovered.add(s));}
const S={level:+saved.level||+legacy.level||1,gold:+saved.gold||+legacy.gold||0,nug:+saved.nug||+legacy.nug||0,xp:+saved.xp||+legacy.xp||0,tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:saved.muted??legacy.muted??false,par:0,solution:[],reactionStep:0,reactionIndex:+saved.reactionIndex||0,artifacts:Array.isArray(saved.artifacts)?saved.artifacts:(Array.isArray(legacy.artifacts)?legacy.artifacts:[]),hazards:+saved.hazards||+legacy.hazards||0,contam:{},usedEvents:new Set(),journal:Array.isArray(saved.journal)?saved.journal:[]};
function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function persist(){localStorage.setItem('cl25_state',JSON.stringify({level:S.level,gold:S.gold,nug:S.nug,xp:S.xp,muted:S.muted,reactionIndex:S.reactionIndex,artifacts:S.artifacts,hazards:S.hazards,discovered:[...discovered],journal:S.journal.slice(-100)}));localStorage.setItem('cl12_discovered_elements',JSON.stringify([...discovered]));$('gold').textContent=S.gold;$('nugget').textContent=S.nug}
function campaignUnlock(){const count=Math.max(3,Math.min(CAMPAIGN,S.level+2));let fresh=null;for(let i=0;i<count;i++){const s=DISCOVERY[i];if(!discovered.has(s)){discovered.add(s);fresh=s}}if(fresh){S.journal.push({type:'element',symbol:fresh,level:S.level,ts:Date.now()});setTimeout(()=>toast(`Відкрито новий елемент: ${fresh}`),250)}persist()}
function pool(){const d=[...discovered],max=Math.min(5,3+Math.floor((S.level-1)/5));if(d.length<=max)return d;const r=[];for(let i=0;i<max;i++)r.push(d[(S.level*2+i*3)%d.length]);return [...new Set(r)].slice(0,max)}
function topRun(t){if(!t.length)return 0;const x=t.at(-1);let n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}
function isLocked(i){return (S.contam[i]||0)>0}
function legal(T,a,b){const A=T[a],B=T[b];if(a===b||!A?.length||!B||B.length>=CAP)return 0;const x=A.at(-1);if(B.length&&B.at(-1)!==x)return 0;return Math.min(topRun(A),CAP-B.length)}
function apply(T,a,b,n){for(let i=0;i<n;i++)T[b].push(T[a].pop())}
function cleared(){return S.tubes.every(t=>!t.length)}
function rng(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}
function reverseCandidates(T){const out=[];for(let a=0;a<T.length;a++){const A=T[a];if(!A.length)continue;const x=A.at(-1),run=topRun(A);for(let b=0;b<T.length;b++){if(a===b||T[b].length>=CAP)continue;const B=T[b];if(B.length&&B.at(-1)===x)continue;for(let n=1;n<=Math.min(run,CAP-B.length);n++){const remain=A.length-n;if(remain>0&&A[remain-1]!==x)continue;out.push([a,b,n])}}}return out}
function validateSolution(start,solution){const T=clone(start);for(const [a,b,n] of solution){const l=legal(T,a,b);if(l<n)return false;apply(T,a,b,n)}return T.every(t=>!t.length||(t.length===CAP&&t.every(x=>x===t[0])))}
function build(seedOffset=0){const colors=pool(),r=rng(S.level*7919+seedOffset*104729+31);for(let attempt=0;attempt<40;attempt++){const T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);const solution=[];const steps=14+colors.length*4+Math.min(S.level,12);let prev='';for(let s=0;s<steps;s++){let c=reverseCandidates(T).filter(m=>`${m[1]}-${m[0]}`!==prev);if(!c.length)c=reverseCandidates(T);if(!c.length)break;const m=c[Math.floor(r()*c.length)];apply(T,m[0],m[1],m[2]);solution.unshift([m[1],m[0],m[2]]);prev=`${m[0]}-${m[1]}`}
 const mixed=T.filter(t=>new Set(t).size>1).length;if(mixed>=Math.min(2,colors.length)&&validateSolution(T,solution)){S.par=solution.length;S.solution=solution;return T}}
 const T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);S.solution=[];S.par=colors.length;return T}
function rankUI(){let r=RANKS[0];for(const x of RANKS)if(S.xp>=x.x)r=x;const i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function availableReactions(){return REACTIONS.filter(r=>r.need.every(x=>discovered.has(x)))}
function reaction(){const a=availableReactions();if(!a.length)return REACTIONS[0];S.reactionIndex%=a.length;return a[S.reactionIndex]}
function stationUI(){const r=reaction(),box=$('recipe');if(!box)return;box.innerHTML='';r.need.forEach((sym,i)=>{if(i){const p=document.createElement('span');p.className='arrow';p.textContent='+';box.appendChild(p)}const s=document.createElement('div');s.className='slot '+(i<S.reactionStep?'done':i===S.reactionStep?'next':'');s.textContent=sym;box.appendChild(s)});const ar=document.createElement('span');ar.className='arrow';ar.textContent='→';box.appendChild(ar);const p=document.createElement('div');p.className='slot product';p.textContent=r.formula;box.appendChild(p);$('stationText').innerHTML=`Побічний синтез · ${r.eq}<br><span style="opacity:.72">Колекційний дослід · ${r.name}</span>`}
function eventPair(a,b){if(a<0||b<0||a===b)return null;const A=S.tubes[a],B=S.tubes[b];if(!A?.length||!B?.length)return null;return [A.at(-1),B.at(-1)]}
function eventFor(list,a,b){const p=eventPair(a,b);return p?list.find(e=>e.pair.every(x=>p.includes(x))&&!S.usedEvents.has(e.id))||null:null}
function render(){const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';wrap.dataset.index=i;const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(isLocked(i)){el.className+=' contaminated';el.dataset.contam=S.contam[i]}else if(S.sel>=0&&i!==S.sel){const sec=eventFor(SECRETS,S.sel,i),haz=eventFor(HAZARDS,S.sel,i);if(haz)el.className+=' risky';else el.className+=(legal(S.tubes,S.sel,i)||sec)?' valid':' dim'}const inn=document.createElement('div');inn.className='tube-inner';tube.forEach((s,li)=>{const e=E[s],d=document.createElement('div');d.className='layer';d.dataset.slot=li;d.style.bottom=`calc(5px + ${li} * ((100% - 12px)/4))`;d.style.background=`linear-gradient(180deg,${e.c2},${e.c})`;d.style.setProperty('--glow',e.c+'66');const label=document.createElement('span');label.className='fluid-symbol';label.textContent=s;d.appendChild(label);inn.appendChild(d)});el.appendChild(inn);wrap.appendChild(el);bindTube(wrap,i);board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;$('levelSub').textContent=`Відкрито ${discovered.size}/118 · У рівні: ${[...new Set(S.tubes.flat())].join(', ')}`;$('footerLevel').textContent=`Кампанія ${Math.min(S.level,CAMPAIGN)} / ${CAMPAIGN} ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();stationUI();persist();window.dispatchEvent(new CustomEvent('chemlab:state',{detail:{level:S.level,discovered:[...discovered],artifacts:S.artifacts,journal:S.journal}}))}
function bindTube(wrap,i){let down=null;wrap.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button===0){down={x:e.clientX,y:e.clientY,id:e.pointerId};try{wrap.setPointerCapture(e.pointerId)}catch{}}},{passive:true});wrap.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId)return;const d=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(d<=10){e.preventDefault();tap(i)}});wrap.addEventListener('pointercancel',()=>down=null)}
function start(level){S.level=Math.max(1,Math.min(CAMPAIGN,level));campaignUnlock();S.tubes=build();S.sel=-1;S.hist=[];S.moves=Math.max(22,S.par+10);S.undo=3;S.shuffle=3;S.hints=3;S.extra=false;S.busy=false;S.contam={};S.usedEvents=new Set();render()}
function makeStream(x1,y1,x2,y2,color,duration=1150){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','liquid-stream-svg');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','liquid-stream-path');p.style.setProperty('--pourColor',color);p.setAttribute('d',`M ${x1} ${y1} C ${x1} ${y1+48}, ${x2} ${y2-38}, ${x2} ${y2}`);svg.appendChild(p);document.body.appendChild(svg);const len=p.getTotalLength();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;p.animate([{strokeDashoffset:len,opacity:0},{strokeDashoffset:0,opacity:1,offset:.18},{strokeDashoffset:0,opacity:1,offset:.82},{strokeDashoffset:-len*.2,opacity:0}],{duration,easing:'ease-in-out'});setTimeout(()=>svg.remove(),duration+120)}
function liveLiquid(a,n,progress){const src=document.querySelectorAll('.tube')[a];if(!src)return;const layers=[...src.querySelectorAll('.layer')],moved=n*progress;for(let j=0;j<n;j++){const layer=layers[layers.length-1-j];if(!layer)continue;const local=Math.max(0,Math.min(1,moved-j));layer.style.opacity=String(1-local*.9);layer.style.transform=`translateY(${local*12}px) scaleY(${1-local*.38})`}}
function animatePour(a,b,n,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst||!src.animate){done();return}const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=B.left>A.left?1:-1,g=src.cloneNode(true);g.className='tube pour-ghost';Object.assign(g.style,{left:A.left+'px',top:A.top+'px',width:A.width+'px',height:A.height+'px'});document.body.appendChild(g);src.style.opacity='.16';const dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*10,dy=(B.top-A.top)-A.height*.42,tilt=dir*64,duration=2250;const an=g.animate([{transform:'translate3d(0,0,0) rotate(0)',offset:0},{transform:`translate3d(${dx*.42}px,${dy*.36}px,0) rotate(${tilt*.10}deg)`,offset:.22},{transform:`translate3d(${dx}px,${dy}px,0) rotate(${tilt}deg)`,offset:.44},{transform:`translate3d(${dx}px,${dy+2}px,0) rotate(${tilt}deg)`,offset:.78},{transform:`translate3d(${dx*.58}px,${dy*.48}px,0) rotate(${tilt*.18}deg)`,offset:.91},{transform:'translate3d(0,0,0) rotate(0)',offset:1}],{duration,easing:'cubic-bezier(.2,.68,.18,1)',fill:'forwards'});const pourStart=800,pourDur=980;setTimeout(()=>{const x=B.left+B.width/2,y=B.top+8;makeStream(x-dir*18,y-72,x,y,color,pourDur);dst.classList.add('receiving');const t0=performance.now();const tick=now=>{const p=Math.min(1,(now-t0)/pourDur);liveLiquid(a,n,p);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);setTimeout(()=>dst.classList.remove('receiving'),1200)},pourStart);Promise.resolve(an.finished).catch(()=>{}).finally(()=>{src.style.opacity='';g.remove();done()})}
function fxAt(i,color,kind='burst'){const tube=document.querySelectorAll('.tube')[i];if(!tube)return;const r=tube.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height*.45;const ring=document.createElement('i');ring.className='reaction-fx reaction-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--fx',color);document.body.appendChild(ring);setTimeout(()=>ring.remove(),1000);for(let n=0;n<14;n++){const p=document.createElement('i');p.className='reaction-fx '+(kind==='crystal'?'reaction-crystal':'reaction-particle');p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--fx',color);p.style.setProperty('--dx',(-55+Math.random()*110)+'px');p.style.setProperty('--dy',(-65+Math.random()*100)+'px');p.style.setProperty('--rot',(-90+Math.random()*180)+'deg');document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}}
function completeTube(i){const t=S.tubes[i];if(t.length!==CAP||!t.every(x=>x===t[0]))return Promise.resolve(false);const sym=t[0],color=E[sym].c,tube=document.querySelectorAll('.tube')[i];S.busy=true;tube?.classList.add('completing');return new Promise(res=>setTimeout(()=>{fxAt(i,color,['Au','Fe'].includes(sym)?'crystal':'burst');S.gold+=12;S.xp+=3;setTimeout(()=>{S.tubes[i]=[];S.busy=false;toast(`${sym}: зразок очищено · +12 ◆`);render();res(true)},620)},850))}
function banner(title,text,cls='secret-banner'){const d=document.createElement('div');d.className=cls;d.innerHTML=`<b>${title}</b>${text}`;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function tickContam(){for(const k of Object.keys(S.contam)){S.contam[k]--;if(S.contam[k]<=0)delete S.contam[k]}}
function doSecret(a,b,e){S.usedEvents.add(e.id);S.gold+=e.bonus;let artifact=null;if(Math.random()<.32){artifact=e.artifact;S.artifacts.push({name:artifact,level:S.level,ts:Date.now()});S.nug++;S.journal.push({type:'artifact',name:artifact,level:S.level,ts:Date.now()})}S.sel=-1;fxAt(b,e.fx,e.kind);banner(e.title,`+${e.bonus} ◆${artifact?` · АРТЕФАКТ: ${artifact}`:''}`);tickContam();render()}
function doHazard(a,b,h){S.usedEvents.add(h.id);S.hazards++;const jackpot=Math.random()<.30;S.sel=-1;if(jackpot){S.gold+=h.jackpot;S.nug+=2;S.artifacts.push({name:h.artifact,level:S.level,ts:Date.now()});S.journal.push({type:'artifact',name:h.artifact,level:S.level,ts:Date.now()});banner('РИЗИК ВИПРАВДАНО',`+${h.jackpot} ◆ · +2 ◇ · ${h.artifact}`,'hazard-banner')}else{S.gold=Math.max(0,S.gold-h.penalty);S.contam[b]=h.contam;banner(h.title,`${h.status} · −${h.penalty} ◆ · блокування ${h.contam} ходи`,'hazard-banner')}fxAt(b,h.fx,jackpot?'crystal':'burst');render()}
async function tap(i){if(S.busy)return;if(isLocked(i)){toast(`Пробірка заблокована ще ${S.contam[i]} ходи`);return}if(S.sel<0){if(!S.tubes[i].length)return;S.sel=i;$('hint').textContent='Обери підсвічену пробірку';render();return}if(S.sel===i){S.sel=-1;render();return}const a=S.sel;if(isLocked(a)){S.sel=-1;render();return}const n=legal(S.tubes,a,i),sec=eventFor(SECRETS,a,i),haz=eventFor(HAZARDS,a,i);if(!n&&haz){doHazard(a,i,haz);return}if(!n&&sec){doSecret(a,i,sec);return}if(!n){document.querySelectorAll('.tube')[i]?.classList.add('shake');S.sel=-1;setTimeout(render,320);return}const before={tubes:clone(S.tubes),moves:S.moves,contam:clone(S.contam)};S.hist.push(before);const next=clone(S.tubes);apply(next,a,i,n);S.busy=true;const color=E[S.tubes[a].at(-1)].c;animatePour(a,i,n,color,async()=>{S.tubes=next;S.moves--;S.sel=-1;tickContam();S.busy=false;render();await completeTube(i);end()})}
function end(){if(cleared()){const rw=40+Math.min(S.level,50)*5,xp=24+Math.min(S.level,50)*3;S.gold+=rw;S.xp+=xp;persist();$('winReward').textContent=`+${rw} ◆`;$('winXp').textContent=`+${xp} XP · відкрито ${discovered.size}/118`;$('win').classList.add('show')}else if(S.moves<=0)$('lose').classList.add('show')}
function bestHint(){for(const [a,b] of S.solution){if(!isLocked(a)&&!isLocked(b)&&legal(S.tubes,a,b))return[a,b]}for(let a=0;a<S.tubes.length;a++)for(let b=0;b<S.tubes.length;b++)if(!isLocked(a)&&!isLocked(b)&&legal(S.tubes,a,b))return[a,b];return null}
$('undo').onclick=()=>{if(S.busy)return;if(S.undo<=0)return toast('Скасування закінчились');const h=S.hist.pop();if(!h)return toast('Немає ходу для скасування');S.tubes=h.tubes;S.moves=h.moves;S.contam=h.contam;S.undo--;S.sel=-1;render()};
$('shuffle').onclick=()=>{if(S.busy)return;if(S.shuffle<=0)return toast('Перемішування закінчились');S.shuffle--;S.tubes=build(Date.now()%10007);S.hist=[];S.contam={};S.moves=Math.max(S.moves,S.par+8);S.sel=-1;render();toast('Новий гарантовано валідований розклад')};
$('addTube').onclick=()=>{if(S.busy)return;if(S.extra)return toast('Додаткова пробірка вже встановлена');S.tubes.push([]);S.extra=true;render();toast('Додано порожню пробірку')};
$('hintBtn').onclick=()=>{if(S.busy)return;if(S.hints<=0)return toast('Підказки закінчились');const h=bestHint();if(!h)return toast('Спробуй перемішати рівень');S.hints--;S.sel=h[0];render();toast(`Підказка: ${h[0]+1} → ${h[1]+1}`)};
$('station').onclick=()=>{if(S.busy)return;const r=reaction(),need=r.need[S.reactionStep];if(S.sel<0)return toast(`Обери зразок ${need}`);const t=S.tubes[S.sel],sym=t?.at(-1);if(sym!==need){S.sel=-1;render();return toast(`Для ${r.formula} потрібен ${need}`)}S.reactionStep++;S.sel=-1;if(S.reactionStep>=r.need.length){S.reactionStep=0;S.reactionIndex++;S.gold+=15;S.journal.push({type:'compound',formula:r.formula,name:r.name,level:S.level,ts:Date.now()});persist();toast(`Синтезовано ${r.formula} · +15 ◆`)}else toast(`${sym} додано до синтезу`);render()};
$('next').onclick=()=>{$('win').classList.remove('show');if(S.level>=CAMPAIGN){toast('Усі 118 елементів відкрито · сектор 119+ активовано');start(CAMPAIGN)}else start(S.level+1)};
$('more').onclick=()=>{$('lose').classList.remove('show');S.moves+=3;render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level)};
$('sound').onclick=()=>{S.muted=!S.muted;persist();$('sound').textContent=S.muted?'🔇':'🔊'};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');
window.ChemLab25={getState:()=>({level:S.level,discovered:[...discovered],artifacts:clone(S.artifacts),journal:clone(S.journal)}),symbols:SYMBOLS};start(S.level);
})();
