(()=>{
'use strict';
const CAP=4;
const E={
 ruby:{s:'Na',n:'Натрій',c:'#ff535d',c2:'#ff8c94'},emerald:{s:'Cl',n:'Хлор',c:'#35e68b',c2:'#79f2b1'},citrine:{s:'Fe',n:'Ферум',c:'#ffb43f',c2:'#ffd071'},
 sapphire:{s:'O',n:'Кисень',c:'#20b9ff',c2:'#64d4ff'},amethyst:{s:'C',n:'Карбон',c:'#9c57f6',c2:'#c18cff'},frost:{s:'H',n:'Гідроген',c:'#4fe0e7',c2:'#92f0f3'},rose:{s:'Au',n:'Аурум',c:'#ffd84d',c2:'#fff08e'}
};
const ORDER=['ruby','emerald','citrine','sapphire','amethyst','frost','rose'];
const MILESTONES=[[1,'ruby'],[1,'emerald'],[1,'citrine'],[4,'sapphire'],[8,'amethyst'],[12,'frost'],[16,'rose']];
const RANKS=[{x:0,n:'Учень алхімік'},{x:120,n:'Лаборант'},{x:350,n:'Хімік'},{x:800,n:'Магістр реакцій'},{x:1600,n:'Архіалхімік'}];
const REACTIONS=[
 {formula:'NaCl',name:'Хлорид натрію',eq:'2Na + Cl₂ → 2NaCl',need:['Na','Cl']},
 {formula:'H₂O',name:'Вода',eq:'2H₂ + O₂ → 2H₂O',need:['H','O']},
 {formula:'Fe₂O₃',name:'Оксид заліза(III)',eq:'4Fe + 3O₂ → 2Fe₂O₃',need:['Fe','O']},
 {formula:'CO₂',name:'Діоксид карбону',eq:'C + O₂ → CO₂',need:['C','O']}
];
const SECRETS=[
 {id:'nacl',pair:['Na','Cl'],kind:'crystal',title:'СЕКРЕТ: КРИСТАЛІЗАЦІЯ',bonus:28,fx:'#b7fff0',artifact:'Кристал солі'},
 {id:'ho',pair:['H','O'],kind:'flash',title:'СЕКРЕТ: ЕНЕРГЕТИЧНИЙ СПАЛАХ',bonus:35,fx:'#7ee9ff',artifact:'Плазмовий уламок'},
 {id:'feo',pair:['Fe','O'],kind:'crystal',title:'СЕКРЕТ: ОКСИДНИЙ КРИСТАЛ',bonus:32,fx:'#ff9f42',artifact:'Оксидний фрагмент'},
 {id:'co',pair:['C','O'],kind:'burst',title:'СЕКРЕТ: ВУГЛЕЦЕВИЙ ІМПУЛЬС',bonus:30,fx:'#b86cff',artifact:'Темний каталізатор'}
];
/* Fictional gameplay hazards only; no preparation instructions or real-world lab conditions. */
const HAZARDS=[
 {id:'tox',pair:['Na','O'],title:'НЕСТАБІЛЬНА ТОКСИЧНА ФАЗА',penalty:18,fx:'#9dff5b',status:'☠ токсична фаза',contam:2,jackpot:42,artifact:'Стабілізований токсик-фрагмент'},
 {id:'cor',pair:['Fe','C'],title:'КОРОЗІЙНИЙ КОМПЛЕКС',penalty:14,fx:'#ff7a3d',status:'⚠ корозійний продукт',contam:2,jackpot:38,artifact:'Корозійний каталізатор'},
 {id:'iso',pair:['Au','O'],title:'АНОМАЛЬНИЙ ІЗОТОП',penalty:24,fx:'#d8ff38',status:'☢ нестабільний ізотоп',contam:3,jackpot:55,artifact:'Ізотопний уламок'}
];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
const key='cl24_state';
let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}
let S={level:+saved.level||+localStorage.cl9_level||1,gold:+saved.gold||+localStorage.cl9_gold||0,nug:+saved.nug||+localStorage.cl9_nug||0,xp:+saved.xp||+localStorage.cl9_xp||0,unlocked:[],tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:saved.muted??(localStorage.cl9_muted==='1'),par:0,solution:[],reactionStep:0,reactionIndex:+saved.reactionIndex||0,artifacts:Array.isArray(saved.artifacts)?saved.artifacts:[],hazards:+saved.hazards||0,contam:{},usedEvents:new Set()};
function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
function persist(){const p={level:S.level,gold:S.gold,nug:S.nug,xp:S.xp,unlocked:S.unlocked,muted:S.muted,reactionIndex:S.reactionIndex,artifacts:S.artifacts,hazards:S.hazards};localStorage.setItem(key,JSON.stringify(p));localStorage.cl9_level=S.level;localStorage.cl9_gold=S.gold;localStorage.cl9_nug=S.nug;localStorage.cl9_xp=S.xp;localStorage.cl9_unlock=JSON.stringify(S.unlocked);$('gold').textContent=S.gold;$('nugget').textContent=S.nug}
function syncUnlocks(){const should=MILESTONES.filter(([l])=>S.level>=l).map(([,k])=>k);S.unlocked=[...new Set(should)].sort((a,b)=>ORDER.indexOf(a)-ORDER.indexOf(b));persist()}
function topRun(t){if(!t.length)return 0;const x=t.at(-1);let n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}
function isLocked(i){return (S.contam[i]||0)>0}
function legal(T,a,b){const A=T[a],B=T[b];if(a===b||!A?.length||!B||B.length>=CAP)return 0;const x=A.at(-1);if(B.length&&B.at(-1)!==x)return 0;return Math.min(topRun(A),CAP-B.length)}
function apply(T,a,b,n){for(let i=0;i<n;i++)T[b].push(T[a].pop())}
function cleared(){return S.tubes.every(t=>!t.length)}
function rng(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}
function activeColors(){return S.unlocked.slice(0,Math.min(3+Math.floor((S.level-1)/4),5,S.unlocked.length))}
function reverseCandidates(T){const out=[];for(let a=0;a<T.length;a++){const A=T[a];if(!A.length)continue;const x=A.at(-1),run=topRun(A);for(let b=0;b<T.length;b++){if(a===b||T[b].length>=CAP)continue;const B=T[b];if(B.length&&B.at(-1)===x)continue;for(let n=1;n<=Math.min(run,CAP-B.length);n++){const remain=A.length-n;if(remain>0&&A[remain-1]!==x)continue;out.push([a,b,n])}}}return out}
function build(seedOffset=0){const colors=activeColors(),r=rng(S.level*7919+seedOffset*104729+31);for(let attempt=0;attempt<24;attempt++){
 const T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);const solution=[];let steps=14+colors.length*4+Math.min(S.level,8),prev='';
 for(let s=0;s<steps;s++){let c=reverseCandidates(T).filter(m=>`${m[1]}-${m[0]}`!==prev);if(!c.length)c=reverseCandidates(T);if(!c.length)break;const m=c[Math.floor(r()*c.length)];apply(T,m[0],m[1],m[2]);solution.unshift([m[1],m[0],m[2]]);prev=`${m[0]}-${m[1]}`}
 const mixed=T.filter(t=>new Set(t).size>1).length;if(mixed>=Math.min(2,colors.length)&&validateSolution(T,solution)){S.par=solution.length;S.solution=solution;return T}
 }
 const T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);const solution=[];for(let i=0;i<colors.length;i++){apply(T,i,colors.length,1);solution.unshift([colors.length,i,1])}S.par=solution.length;S.solution=solution;return T
}
function validateSolution(start,solution){const T=clone(start);for(const [a,b,n] of solution){const l=legal(T,a,b);if(l<n)return false;apply(T,a,b,n)}return T.every(t=>!t.length||(t.length===CAP&&t.every(x=>x===t[0])))}
function rankUI(){let r=RANKS[0];for(const x of RANKS)if(S.xp>=x.x)r=x;const i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function reaction(){const syms=new Set(S.unlocked.map(k=>E[k].s)),available=REACTIONS.filter(r=>r.need.every(x=>syms.has(x)));if(!available.length)return REACTIONS[0];S.reactionIndex%=available.length;return available[S.reactionIndex]}
function stationUI(){const r=reaction(),box=$('recipe');if(!box)return;box.innerHTML='';r.need.forEach((sym,i)=>{if(i){const p=document.createElement('span');p.className='arrow';p.textContent='+';box.appendChild(p)}const s=document.createElement('div');s.className='slot '+(i<S.reactionStep?'done':i===S.reactionStep?'next':'');s.textContent=sym;box.appendChild(s)});const ar=document.createElement('span');ar.className='arrow';ar.textContent='→';box.appendChild(ar);const p=document.createElement('div');p.className='slot product';p.textContent=r.formula;box.appendChild(p);$('stationText').innerHTML=`Побічний синтез · ${r.eq}<br><span style="opacity:.72">Не впливає на баланс puzzle · ${r.name}</span>`}
function render(){const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';wrap.dataset.index=i;const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(isLocked(i)){el.className+=' contaminated';el.dataset.contam=S.contam[i]}else if(S.sel>=0&&i!==S.sel){const sec=eventFor(SECRETS,S.sel,i),haz=eventFor(HAZARDS,S.sel,i);if(haz)el.className+=' risky';else el.className+=(legal(S.tubes,S.sel,i)||sec)?' valid':' dim'}const inn=document.createElement('div');inn.className='tube-inner';tube.forEach((k,li)=>{const e=E[k],d=document.createElement('div');d.className='layer';d.dataset.slot=li;d.style.bottom=`calc(5px + ${li} * ((100% - 12px)/4))`;d.style.background=`linear-gradient(180deg,${e.c2},${e.c})`;d.style.setProperty('--glow',e.c+'66');const label=document.createElement('span');label.className='fluid-symbol';label.textContent=e.s;d.appendChild(label);inn.appendChild(d)});el.appendChild(inn);wrap.appendChild(el);bindTube(wrap,i);board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;$('levelSub').textContent='Реагенти: '+[...new Set(S.tubes.flat())].map(k=>E[k].s).join(', ');$('footerLevel').textContent=`Рівень ${S.level} з 50 ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();stationUI();persist()}
function bindTube(wrap,i){let down=null;wrap.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button===0){down={x:e.clientX,y:e.clientY,id:e.pointerId};try{wrap.setPointerCapture(e.pointerId)}catch{}}},{passive:true});wrap.addEventListener('pointerup',e=>{if(!down||down.id!==e.pointerId)return;const d=Math.hypot(e.clientX-down.x,e.clientY-down.y);down=null;if(d<=10){e.preventDefault();tap(i)}});wrap.addEventListener('pointercancel',()=>down=null)}
function start(level){S.level=Math.max(1,level);syncUnlocks();S.tubes=build();S.sel=-1;S.hist=[];S.moves=Math.max(22,S.par+10);S.undo=3;S.shuffle=3;S.hints=3;S.extra=false;S.busy=false;S.contam={};S.usedEvents=new Set();render()}
function makeStream(x1,y1,x2,y2,color,duration=1100){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','liquid-stream-svg');const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('class','liquid-stream-path');p.style.setProperty('--pourColor',color);p.setAttribute('d',`M ${x1} ${y1} C ${x1} ${y1+48}, ${x2} ${y2-38}, ${x2} ${y2}`);svg.appendChild(p);document.body.appendChild(svg);const len=p.getTotalLength();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;p.animate([{strokeDashoffset:len,opacity:0},{strokeDashoffset:0,opacity:1,offset:.18},{strokeDashoffset:0,opacity:1,offset:.82},{strokeDashoffset:-len*.2,opacity:0}],{duration,easing:'ease-in-out'});setTimeout(()=>svg.remove(),duration+120)}
function liveLiquid(a,n,progress){const src=document.querySelectorAll('.tube')[a];if(!src)return;const layers=[...src.querySelectorAll('.layer')],moved=n*progress;for(let j=0;j<n;j++){const layer=layers[layers.length-1-j];if(!layer)continue;const local=Math.max(0,Math.min(1,moved-j));layer.style.opacity=String(1-local*.9);layer.style.transform=`translateY(${local*12}px) scaleY(${1-local*.38})`}}
function animatePour(a,b,n,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst||!src.animate){done();return}const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=B.left>A.left?1:-1,g=src.cloneNode(true);g.className='tube pour-ghost';Object.assign(g.style,{left:A.left+'px',top:A.top+'px',width:A.width+'px',height:A.height+'px'});document.body.appendChild(g);src.style.opacity='.16';const dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*10,dy=(B.top-A.top)-A.height*.42,tilt=dir*64,duration=2200;const an=g.animate([{transform:'translate3d(0,0,0) rotate(0)',offset:0},{transform:`translate3d(${dx*.42}px,${dy*.36}px,0) rotate(${tilt*.10}deg)`,offset:.22},{transform:`translate3d(${dx}px,${dy}px,0) rotate(${tilt}deg)`,offset:.44},{transform:`translate3d(${dx}px,${dy+2}px,0) rotate(${tilt}deg)`,offset:.78},{transform:`translate3d(${dx*.58}px,${dy*.48}px,0) rotate(${tilt*.16}deg)`,offset:.91},{transform:'translate3d(0,0,0) rotate(0)',offset:1}],{duration,easing:'cubic-bezier(.2,.66,.18,1)',fill:'forwards'});const pourStart=820,pourDur=1000;setTimeout(()=>{const x=B.left+B.width/2,y=B.top+8;makeStream(x-dir*18,y-72,x,y,color,pourDur);dst.classList.add('receiving');const t0=performance.now(),tick=now=>{const p=Math.min(1,(now-t0)/pourDur);liveLiquid(a,n,p);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);setTimeout(()=>dst.classList.remove('receiving'),1200)},pourStart);Promise.resolve(an.finished).catch(()=>{}).finally(()=>{src.style.opacity='';g.remove();done()})}
function fxAt(i,color,kind='burst'){const tube=document.querySelectorAll('.tube')[i];if(!tube)return;const r=tube.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height*.45;const ring=document.createElement('i');ring.className='reaction-fx reaction-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--fx',color);document.body.appendChild(ring);setTimeout(()=>ring.remove(),1000);for(let n=0;n<12;n++){const p=document.createElement('i');p.className='reaction-fx '+(kind==='crystal'?'reaction-crystal':'reaction-particle');p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--fx',color);p.style.setProperty('--dx',(-55+Math.random()*110)+'px');p.style.setProperty('--dy',(-65+Math.random()*100)+'px');p.style.setProperty('--rot',(-90+Math.random()*180)+'deg');document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}}
function completeTube(i){const t=S.tubes[i];if(t.length!==CAP||!t.every(x=>x===t[0]))return Promise.resolve(false);const key=t[0],tube=document.querySelectorAll('.tube')[i];S.busy=true;tube?.classList.add('completing');return new Promise(res=>setTimeout(()=>{fxAt(i,E[key].c,key==='rose'||key==='citrine'?'crystal':'burst');S.gold+=12;setTimeout(()=>{S.tubes[i]=[];S.busy=false;toast(`${E[key].n}: зразок очищено · +12 ◆`);render();res(true)},620)},820))}
function pairFor(a,b){if(a<0||b<0||a===b)return null;const A=S.tubes[a],B=S.tubes[b];if(!A?.length||!B?.length)return null;return [E[A.at(-1)].s,E[B.at(-1)].s]}
function eventFor(list,a,b){if(isLocked(a)||isLocked(b))return null;const p=pairFor(a,b);return p?list.find(x=>x.pair.every(s=>p.includes(s)))||null:null}
function banner(title,text,cls='secret-banner'){const d=document.createElement('div');d.className=cls;d.innerHTML=`<b>${title}</b>${text}`;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function tickContam(){for(const k of Object.keys(S.contam)){S.contam[k]--;if(S.contam[k]<=0)delete S.contam[k]}}
function doSecret(a,b,sec){if(S.usedEvents.has('s:'+sec.id))return toast('Цю пасхалку вже активовано на рівні');S.usedEvents.add('s:'+sec.id);S.busy=true;animatePour(a,b,1,sec.fx,()=>{S.moves--;S.gold+=sec.bonus;let artifact=null;if(Math.random()<.28){artifact=sec.artifact;S.artifacts.push({name:artifact,level:S.level,ts:Date.now()});S.nug++}S.sel=-1;fxAt(b,sec.fx,sec.kind);banner(sec.title,`+${sec.bonus} ◆${artifact?` · АРТЕФАКТ: ${artifact}`:''}`);S.busy=false;tickContam();render();end()})}
function doHazard(a,b,haz){if(S.usedEvents.has('h:'+haz.id))return toast('Цей ризик уже перевірено на рівні');S.usedEvents.add('h:'+haz.id);S.busy=true;animatePour(a,b,1,haz.fx,()=>{S.moves--;S.hazards++;S.sel=-1;const success=Math.random()<.30;if(success){S.gold+=haz.jackpot;S.nug+=2;S.artifacts.push({name:haz.artifact,level:S.level,ts:Date.now()});banner('АНОМАЛІЮ СТАБІЛІЗОВАНО',`+${haz.jackpot} ◆ · +2 ◇ · ${haz.artifact}`,'secret-banner')}else{S.gold=Math.max(0,S.gold-haz.penalty);S.contam[b]=haz.contam;banner(haz.title,`${haz.status} · −${haz.penalty} ◆ · пробірка заблокована`,'hazard-banner')}fxAt(b,haz.fx,success?'crystal':'burst');S.busy=false;tickContam();render();end()})}
async function tap(i){if(S.busy)return;if(isLocked(i))return toast(`Контамінація: ще ${S.contam[i]} ходи`);if(S.sel<0){if(!S.tubes[i].length)return;S.sel=i;$('hint').textContent='Обери підсвічену пробірку';render();return}if(S.sel===i){S.sel=-1;render();return}const a=S.sel,n=legal(S.tubes,a,i),haz=eventFor(HAZARDS,a,i),sec=eventFor(SECRETS,a,i);if(!n&&haz){doHazard(a,i,haz);return}if(!n&&sec){doSecret(a,i,sec);return}if(!n){document.querySelectorAll('.tube')[i]?.classList.add('shake');setTimeout(()=>render(),320);S.sel=-1;return}const before=clone(S.tubes),next=clone(S.tubes);apply(next,a,i,n);S.hist.push({tubes:before,contam:clone(S.contam),moves:S.moves});S.busy=true;const color=E[S.tubes[a].at(-1)].c;animatePour(a,i,n,color,async()=>{S.tubes=next;S.moves--;S.sel=-1;S.busy=false;tickContam();render();await completeTube(i);end()})}
function end(){if(cleared()){const rw=40+S.level*5,xp=20+S.level*3;S.gold+=rw;S.xp+=xp;persist();$('winReward').textContent=`+${rw} ◆`;$('winXp').textContent=`+${xp} XP`;$('win').classList.add('show')}else if(S.moves<=0)$('lose').classList.add('show')}
function bestHint(){for(let a=0;a<S.tubes.length;a++)for(let b=0;b<S.tubes.length;b++)if(!isLocked(a)&&!isLocked(b)&&legal(S.tubes,a,b))return[a,b];return null}
$('undo').onclick=()=>{if(S.busy)return;if(S.undo<=0)return toast('Скасування закінчились');const h=S.hist.pop();if(!h)return toast('Немає ходу для скасування');S.tubes=h.tubes;S.contam=h.contam;S.moves=h.moves;S.undo--;S.sel=-1;render()};
$('shuffle').onclick=()=>{if(S.busy)return;if(S.shuffle<=0)return toast('Перемішування закінчились');S.shuffle--;S.tubes=build(Date.now()%997);S.hist=[];S.contam={};S.moves=Math.max(S.moves,S.par+8);S.sel=-1;render();toast('Новий гарантовано зворотний розклад')};
$('addTube').onclick=()=>{if(S.busy)return;if(S.extra)return toast('Додаткова пробірка вже встановлена');S.tubes.push([]);S.extra=true;render();toast('Додано порожню пробірку')};
$('hintBtn').onclick=()=>{if(S.busy)return;if(S.hints<=0)return toast('Підказки закінчились');const h=bestHint();if(!h)return toast('Немає звичайного ходу — скасуй або перемішай');S.hints--;S.sel=h[0];render();toast(`Підказка: ${h[0]+1} → ${h[1]+1}`)};
$('station').onclick=()=>{if(S.busy)return;const r=reaction(),need=r.need[S.reactionStep];if(S.sel<0)return toast(`Обери зразок ${need}`);const tube=S.tubes[S.sel],sym=tube.length?E[tube.at(-1)].s:null;if(sym!==need){S.sel=-1;render();return toast(`Для ${r.formula} потрібен ${need}`)}S.reactionStep++;S.sel=-1;if(S.reactionStep>=r.need.length){S.reactionStep=0;S.reactionIndex++;S.gold+=15;toast(`Побічний синтез: ${r.formula} · +15 ◆`)}else toast(`${sym} додано до синтезу`);render()};
$('next').onclick=()=>{$('win').classList.remove('show');start(S.level+1)};$('more').onclick=()=>{$('lose').classList.remove('show');S.moves+=3;render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level)};$('sound').onclick=()=>{S.muted=!S.muted;$('sound').textContent=S.muted?'🔇':'🔊';persist()};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');
start(S.level);
})();