(()=>{
const CAP=4;
const E={ruby:{s:'Na',n:'Натрій',c:'#ff535d',c2:'#ff8c94'},emerald:{s:'Cl',n:'Хлор',c:'#35e68b',c2:'#79f2b1'},citrine:{s:'Fe',n:'Ферум',c:'#ffb43f',c2:'#ffd071'},sapphire:{s:'O',n:'Кисень',c:'#20b9ff',c2:'#64d4ff'},amethyst:{s:'C',n:'Карбон',c:'#9c57f6',c2:'#c18cff'},frost:{s:'H',n:'Гідроген',c:'#4fe0e7',c2:'#92f0f3'},rose:{s:'Au',n:'Аурум',c:'#ffd84d',c2:'#fff08e'}};
const START=['ruby','emerald','citrine'];
const RECIPES=[{key:'sapphire',r:['ruby','emerald']},{key:'amethyst',r:['ruby','citrine']},{key:'frost',r:['emerald','sapphire']},{key:'rose',r:['ruby','sapphire','citrine']}];
const RANKS=[{x:0,n:'Учень алхімік'},{x:120,n:'Лаборант'},{x:350,n:'Хімік'},{x:800,n:'Магістр реакцій'},{x:1600,n:'Архіалхімік'}];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x));
let S={level:+localStorage.cl9_level||1,gold:+localStorage.cl9_gold||0,nug:+localStorage.cl9_nug||0,xp:+localStorage.cl9_xp||0,unlocked:JSON.parse(localStorage.cl9_unlock||JSON.stringify(START)),station:+localStorage.cl9_station||0,tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:localStorage.cl9_muted==='1',completed:new Set()};
const save=()=>{localStorage.cl9_level=S.level;localStorage.cl9_gold=S.gold;localStorage.cl9_nug=S.nug;localStorage.cl9_xp=S.xp;localStorage.cl9_unlock=JSON.stringify(S.unlocked);localStorage.cl9_station=S.station;$('gold').textContent=S.gold;$('nugget').textContent=S.nug};
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1500)}
function sh(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function solved(T){return T.every(t=>!t.length||(t.length===CAP&&t.every(x=>x===t[0])))}
function topRun(t){if(!t.length)return 0;let x=t.at(-1),n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}
function legal(T,a,b){const A=T[a],B=T[b];if(a===b||!A.length||B.length>=CAP)return 0;const x=A.at(-1);if(B.length&&B.at(-1)!==x)return 0;return Math.min(topRun(A),CAP-B.length)}
function key(T){return T.map(t=>t.join(',')).sort().join('|')}
function solve(T,limit=50000,wantMove=false){const seen=new Set();let nodes=0;function dfs(X,last){if(solved(X))return [];if(++nodes>limit)return null;const k=key(X);if(seen.has(k))return null;seen.add(k);let ms=[];for(let a=0;a<X.length;a++)for(let b=0;b<X.length;b++){let n=legal(X,a,b);if(!n)continue;if(last&&last[0]===b&&last[1]===a)continue;if(!X[b].length&&topRun(X[a])===X[a].length)continue;const merge=X[b].length?1:0;ms.push([a,b,n,merge])}ms.sort((m1,m2)=>m2[3]-m1[3]);for(const [a,b,n] of ms){const N=clone(X);for(let i=0;i<n;i++)N[b].push(N[a].pop());const r=dfs(N,[a,b]);if(r)return [[a,b],...r]}return null}return dfs(clone(T),null)}
function colorCount(){return Math.min(3+Math.floor((S.level-1)/3),S.unlocked.length,5)}
function reverseScramble(colors){let T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);let steps=12+colors.length*5+Math.min(8,S.level);for(let s=0;s<steps;s++){let candidates=[];for(let a=0;a<T.length;a++){if(!T[a].length)continue;const run=topRun(T[a]),x=T[a].at(-1);for(let b=0;b<T.length;b++){if(a===b||T[b].length>=CAP)continue;const maxTake=Math.min(run,T[b].length?CAP-T[b].length:CAP);for(let n=1;n<=maxTake;n++){const remain=T[a].length-n;if(remain>0&&T[a][remain-1]!==x)continue;if(remain===0||T[a][remain-1]===x)candidates.push([a,b,n])}}}if(!candidates.length)break;const [a,b,n]=candidates[Math.floor(Math.random()*candidates.length)];for(let i=0;i<n;i++)T[b].push(T[a].pop())}return T}
function build(){const colors=sh(S.unlocked.slice()).slice(0,colorCount());for(let i=0;i<80;i++){const T=reverseScramble(colors);if(solved(T))continue;const sol=solve(T,40000);if(sol&&sol.length>=6)return T}const fallback=[];colors.forEach(c=>fallback.push(Array(CAP).fill(c)));fallback.push([],[]);if(colors.length>1){fallback[colors.length].push(fallback[0].pop());fallback[colors.length+1].push(fallback[1].pop())}return fallback}
function rankUI(){let r=RANKS[0];RANKS.forEach(v=>{if(S.xp>=v.x)r=v});let i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function quest(){return RECIPES.find(q=>!S.unlocked.includes(q.key))||null}
function tray(){const tr=$('tray');tr.innerHTML='';Object.keys(E).forEach(k=>{const e=E[k],d=document.createElement('div');d.className='el';d.innerHTML=`<i class="sw" style="background:${e.c}"></i>${e.s} — ${e.n}`;tr.appendChild(d)})}
function station(){const q=quest(),r=$('recipe');r.innerHTML='';if(!q){$('stationText').textContent='Усі реагенти відкрито';return}q.r.forEach((k,i)=>{if(i){const a=document.createElement('span');a.className='arrow';a.textContent='→';r.appendChild(a)}const s=document.createElement('div');s.className='slot '+(i<S.station?'done':i===S.station?'next':'');s.textContent=E[k].s;r.appendChild(s)});$('stationText').textContent=`Відкриє: ${E[q.key].n} (${E[q.key].s})`}
function bubbles(layer){for(let i=0;i<5;i++){const b=document.createElement('i');b.className='bubble';const z=2+Math.random()*4;b.style.width=b.style.height=z+'px';b.style.left=(10+Math.random()*78)+'%';b.style.setProperty('--dur',(1.6+Math.random()*2.4)+'s');b.style.setProperty('--delay',(-Math.random()*3)+'s');b.style.setProperty('--travel',(24+Math.random()*34)+'px');b.style.setProperty('--drift',(-5+Math.random()*10)+'px');layer.appendChild(b)}}
function render(){const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(S.sel>=0&&i!==S.sel)el.className+=legal(S.tubes,S.sel,i)?' valid':' dim';const inn=document.createElement('div');inn.className='tube-inner';tube.forEach((k,li)=>{const e=E[k],d=document.createElement('div');d.className='layer';d.style.bottom=`calc(5px + ${li} * ((100% - 12px)/4))`;d.style.background=`linear-gradient(180deg,${e.c2},${e.c})`;d.style.setProperty('--glow',e.c+'66');d.textContent=e.s;bubbles(d);inn.appendChild(d)});el.appendChild(inn);el.onclick=()=>tap(i);wrap.appendChild(el);board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;$('levelSub').textContent='Реагенти: '+[...new Set(S.tubes.flat())].map(k=>E[k].s).join(', ');$('footerLevel').textContent=`Рівень ${S.level} з 50 ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();tray();station();save()}
function start(level){S.level=level;S.tubes=build();S.sel=-1;S.hist=[];S.completed=new Set();S.moves=Math.max(18,12+colorCount()*4+Math.floor(level/2));S.undo=3;S.shuffle=3;S.hints=3;S.extra=false;S.busy=false;render()}
function animatePour(a,b,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst)return done();const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=(B.left>A.left)?1:-1;const g=src.cloneNode(true);g.className='tube pour-ghost';g.style.left=A.left+'px';g.style.top=A.top+'px';g.style.width=A.width+'px';g.style.height=A.height+'px';document.body.appendChild(g);src.style.opacity='.15';const dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*9,dy=(B.top-A.top)-A.height*.45,tilt=dir*66;const an=g.animate([{transform:'translate(0,0) rotate(0)'},{transform:`translate(${dx*.8}px,${dy*.7}px) rotate(${tilt*.35}deg)`,offset:.38},{transform:`translate(${dx}px,${dy}px) rotate(${tilt}deg)`,offset:.58},{transform:`translate(${dx}px,${dy+2}px) rotate(${tilt}deg)`,offset:.76},{transform:'translate(0,0) rotate(0)'}],{duration:900,easing:'cubic-bezier(.2,.75,.2,1)'});setTimeout(()=>{const x=B.left+B.width/2,y=B.top+10;const s=document.createElement('div');s.className='pour-stream';s.style.left=(x-3)+'px';s.style.top=(y-67)+'px';s.style.height='72px';s.style.setProperty('--pourColor',color);document.body.appendChild(s);for(let i=0;i<9;i++){const p=document.createElement('i');p.className='splash';p.style.left=(x-2)+'px';p.style.top=(y+4)+'px';p.style.setProperty('--pourColor',color);p.style.setProperty('--sx',(-16+Math.random()*32)+'px');p.style.setProperty('--sy',(-13+Math.random()*17)+'px');document.body.appendChild(p);setTimeout(()=>p.remove(),560)}setTimeout(()=>s.remove(),720)},460);an.finished.finally(()=>{src.style.opacity='';g.remove();done()})}
function tap(i){if(S.busy)return;if(S.sel<0){if(!S.tubes[i].length)return;S.sel=i;$('hint').textContent='Обери підсвічену колбу';render();return}if(S.sel===i){S.sel=-1;$('hint').textContent='Торкнись колби, щоб обрати реагент';render();return}const n=legal(S.tubes,S.sel,i);if(!n){const e=document.querySelectorAll('.tube')[i];e?.classList.add('shake');setTimeout(()=>e?.classList.remove('shake'),280);S.sel=-1;render();return}const a=S.sel,next=clone(S.tubes);for(let k=0;k<n;k++)next[i].push(next[a].pop());const solv=solved(next)||solve(next,30000);if(!solv){document.querySelectorAll('.tube')[i]?.classList.add('dead');setTimeout(()=>document.querySelectorAll('.tube')[i]?.classList.remove('dead'),500);toast('Цей хід веде в глухий кут');S.sel=-1;render();return}S.busy=true;S.hist.push(clone(S.tubes));const color=E[S.tubes[a].at(-1)].c;animatePour(a,i,color,()=>{S.tubes=next;S.moves--;S.sel=-1;S.busy=false;reward();render();end()})}
function reward(){S.tubes.forEach((t,i)=>{if(t.length===CAP&&t.every(x=>x===t[0])&&!S.completed.has(i)){S.completed.add(i);S.gold+=10;toast('Реакція стабілізована · +10 ◆')}})}
function end(){if(solved(S.tubes)){const rw=35+S.level*5,xp=18+S.level*3;S.gold+=rw;S.xp+=xp;save();$('winReward').textContent=`+${rw} ◆`;$('winXp').textContent=`+${xp} XP`;$('win').classList.add('show')}else if(S.moves<=0)$('lose').classList.add('show')}
$('undo').onclick=()=>{if(S.busy)return;if(S.undo<=0)return toast('Скасування закінчились');if(!S.hist.length)return toast('Немає ходу для скасування');S.tubes=S.hist.pop();S.undo--;S.moves++;S.sel=-1;render()};
$('shuffle').onclick=()=>{if(S.busy)return;if(S.shuffle<=0)return toast('Перемішування закінчились');S.shuffle--;S.tubes=build();S.hist=[];S.sel=-1;render();toast('Новий гарантовано прохідний розклад')};
$('addTube').onclick=()=>{if(S.busy)return;if(S.extra)return toast('Додаткова колба вже встановлена');S.tubes.push([]);S.extra=true;render();toast('Додано порожню колбу')};
$('hintBtn').onclick=()=>{if(S.busy)return;if(S.hints<=0)return toast('Підказки закінчились');const sol=solve(S.tubes,50000,true);if(!sol||!sol.length)return toast('Рішення не знайдено — перемішай рівень');S.hints--;S.sel=sol[0][0];render();toast(`Оптимальний хід: ${sol[0][0]+1} → ${sol[0][1]+1}`)};
$('station').onclick=()=>{if(S.busy)return;const q=quest();if(!q)return toast('Усі реагенти вже відкрито');if(S.sel<0)return toast(`Обери колбу з ${E[q.r[S.station]].s}`);const top=S.tubes[S.sel].at(-1),need=q.r[S.station];if(top!==need)return toast(`Потрібен ${E[need].s}`);S.station++;S.sel=-1;if(S.station>=q.r.length){S.unlocked.push(q.key);S.station=0;save();toast(`Відкрито ${E[q.key].n} (${E[q.key].s})`)}render()};
$('next').onclick=()=>{$('win').classList.remove('show');start(S.level+1)};$('more').onclick=()=>{$('lose').classList.remove('show');S.moves+=3;render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level)};$('sound').onclick=()=>{S.muted=!S.muted;localStorage.cl9_muted=S.muted?'1':'0';$('sound').textContent=S.muted?'🔇':'🔊'};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');start(S.level);
})();
