(()=>{
'use strict';
const CAP=4,NS='http://www.w3.org/2000/svg';
const E={ruby:{s:'Na',n:'Натрій',c:'#ff535d',c2:'#ff8c94'},emerald:{s:'Cl',n:'Хлор',c:'#35e68b',c2:'#79f2b1'},citrine:{s:'Fe',n:'Ферум',c:'#ffb43f',c2:'#ffd071'},sapphire:{s:'O',n:'Кисень',c:'#20b9ff',c2:'#64d4ff'},amethyst:{s:'C',n:'Карбон',c:'#9c57f6',c2:'#c18cff'},frost:{s:'H',n:'Гідроген',c:'#4fe0e7',c2:'#92f0f3'},rose:{s:'Au',n:'Аурум',c:'#ffd84d',c2:'#fff08e'}};
const ORDER=['ruby','emerald','citrine','sapphire','amethyst','frost','rose'];
const MILESTONES=[[1,'ruby'],[1,'emerald'],[1,'citrine'],[4,'sapphire'],[8,'amethyst'],[12,'frost'],[16,'rose']];
const RANKS=[{x:0,n:'Учень алхімік'},{x:120,n:'Лаборант'},{x:350,n:'Хімік'},{x:800,n:'Магістр реакцій'},{x:1600,n:'Архіалхімік'}];
const REACTIONS=[{formula:'NaCl',name:'Хлорид натрію',eq:'2Na + Cl₂ → 2NaCl',need:['Na','Cl']},{formula:'H₂O',name:'Вода',eq:'2H₂ + O₂ → 2H₂O',need:['H','O']},{formula:'Fe₂O₃',name:'Оксид заліза(III)',eq:'4Fe + 3O₂ → 2Fe₂O₃',need:['Fe','O']},{formula:'CO₂',name:'Діоксид карбону',eq:'C + O₂ → CO₂',need:['C','O']}];
const SECRETS=[{pair:['Na','Cl'],kind:'crystal',title:'СЕКРЕТ: КРИСТАЛІЗАЦІЯ',bonus:28,fx:'#b7fff0',artifact:'Кристал солі'},{pair:['H','O'],kind:'flash',title:'СЕКРЕТ: ЕНЕРГЕТИЧНИЙ СПАЛАХ',bonus:35,fx:'#7ee9ff',artifact:'Плазмовий уламок'},{pair:['Fe','O'],kind:'crystal',title:'СЕКРЕТ: ОКСИДНИЙ КРИСТАЛ',bonus:32,fx:'#ff9f42',artifact:'Оксидний фрагмент'},{pair:['C','O'],kind:'burst',title:'СЕКРЕТ: ВУГЛЕЦЕВИЙ ІМПУЛЬС',bonus:30,fx:'#b86cff',artifact:'Темний каталізатор'}];
/* Fictionalized gameplay hazards only; no real preparation instructions. */
const HAZARDS=[{pair:['Na','O'],title:'НЕСТАБІЛЬНА ТОКСИЧНА ФАЗА',penalty:18,fx:'#9dff5b',status:'☠ токсична фаза',contam:2,jackpot:42,artifact:'Стабілізований токсик-фрагмент'},{pair:['Fe','C'],title:'КОРОЗІЙНИЙ КОМПЛЕКС',penalty:14,fx:'#ff7a3d',status:'⚠ корозійний продукт',contam:2,jackpot:38,artifact:'Корозійний каталізатор'},{pair:['Au','O'],title:'АНОМАЛЬНИЙ РАДІОІЗОТОП',penalty:24,fx:'#d8ff38',status:'☢ нестабільний ізотоп',contam:3,jackpot:55,artifact:'Ізотопний уламок'}];
const $=id=>document.getElementById(id),clone=x=>JSON.parse(JSON.stringify(x)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let S={level:+localStorage.cl9_level||1,gold:+localStorage.cl9_gold||0,nug:+localStorage.cl9_nug||0,xp:+localStorage.cl9_xp||0,unlocked:[],tubes:[],sel:-1,moves:0,hist:[],undo:3,shuffle:3,hints:3,extra:false,busy:false,muted:localStorage.cl9_muted==='1',par:0,reactionStep:0,reactionIndex:+localStorage.cl14_reaction||0,artifacts:[],hazards:+localStorage.cl17_hazards||0,contam:{}};
try{S.artifacts=JSON.parse(localStorage.cl15_artifacts||'[]')}catch{}
function haptic(p=8){if(S.muted)return;try{navigator.vibrate?.(p)}catch{}}
function toast(t){const el=$('toast');if(!el)return;el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
function save(){localStorage.cl9_level=S.level;localStorage.cl9_gold=S.gold;localStorage.cl9_nug=S.nug;localStorage.cl9_xp=S.xp;localStorage.cl9_unlock=JSON.stringify(S.unlocked);localStorage.cl14_reaction=S.reactionIndex;localStorage.cl15_artifacts=JSON.stringify(S.artifacts);localStorage.cl17_hazards=S.hazards;$('gold').textContent=S.gold;$('nugget').textContent=S.nug}
function syncUnlocks(){let saved=[];try{saved=JSON.parse(localStorage.cl9_unlock||'[]')}catch{};const should=MILESTONES.filter(([l])=>S.level>=l).map(([,k])=>k);S.unlocked=[...new Set([...ORDER.slice(0,3),...saved.filter(k=>ORDER.includes(k)),...should])].sort((a,b)=>ORDER.indexOf(a)-ORDER.indexOf(b));save()}
function topRun(t){if(!t.length)return 0;const x=t.at(-1);let n=1;for(let i=t.length-2;i>=0&&t[i]===x;i--)n++;return n}
function isLocked(i){return (S.contam[i]||0)>0}
function legal(T,a,b){const A=T[a],B=T[b];if(isLocked(a)||isLocked(b)||a===b||!A?.length||!B||B.length>=CAP)return 0;const x=A.at(-1);if(B.length&&B.at(-1)!==x)return 0;return Math.min(topRun(A),CAP-B.length)}
function cleared(){return S.tubes.every(t=>!t.length)}
function rng(seed){let x=seed|0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return((x>>>0)%100000)/100000}}
function activeColors(){const count=Math.min(3+Math.floor((S.level-1)/4),S.unlocked.length,5);return S.unlocked.slice(0,count)}
function build(seedOffset=0){const colors=activeColors(),r=rng(S.level*7919+seedOffset*104729+31),T=colors.map(c=>Array(CAP).fill(c));T.push([],[]);let steps=14+colors.length*5+Math.min(S.level,8);for(let s=0;s<steps;s++){const cand=[];for(let a=0;a<T.length;a++){if(!T[a].length)continue;const run=topRun(T[a]),x=T[a].at(-1);for(let b=0;b<T.length;b++){if(a===b||T[b].length>=CAP)continue;if(T[b].length&&T[b].at(-1)===x)continue;for(let n=1;n<=Math.min(run,CAP-T[b].length);n++)cand.push([a,b,n])}}if(!cand.length)break;const m=cand[Math.floor(r()*cand.length)];for(let i=0;i<m[2];i++)T[m[1]].push(T[m[0]].pop())}S.par=steps;return T}
function rankUI(){let r=RANKS[0];for(const x of RANKS)if(S.xp>=x.x)r=x;const i=RANKS.indexOf(r),nx=RANKS[i+1];$('rankName').textContent=r.n;$('xpFill').style.width=nx?Math.min(100,(S.xp-r.x)/(nx.x-r.x)*100)+'%':'100%';$('xpText').textContent=nx?`${S.xp} / ${nx.x} XP`:`${S.xp} XP · MAX`}
function reaction(){const syms=new Set(S.unlocked.map(k=>E[k].s)),available=REACTIONS.filter(r=>r.need.every(x=>syms.has(x)));if(!available.length)return REACTIONS[0];S.reactionIndex%=available.length;return available[S.reactionIndex]}
function stationUI(){const r=reaction(),box=$('recipe');if(!box)return;box.innerHTML='';r.need.forEach((sym,i)=>{if(i){const p=document.createElement('span');p.className='arrow';p.textContent='+';box.appendChild(p)}const s=document.createElement('div');s.className='slot '+(i<S.reactionStep?'done':i===S.reactionStep?'next':'');s.textContent=sym;box.appendChild(s)});const ar=document.createElement('span');ar.className='arrow';ar.textContent='→';box.appendChild(ar);const p=document.createElement('div');p.className='slot product';p.textContent=r.formula;box.appendChild(p);$('stationText').innerHTML=`${r.eq}<br><span style="opacity:.72">Продукт: ${r.name}</span>`}
function mk(tag,attrs={}){const e=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));return e}
function wave(y,amp,phase=0){return`M 7 ${y} C 22 ${y-amp+phase},38 ${y+amp},50 ${y} C 64 ${y-amp},79 ${y+amp-phase},93 ${y}`}
function fluidSvg(tube,id){const svg=mk('svg',{class:'fluid-v21',viewBox:'0 0 100 400',preserveAspectRatio:'none'});const defs=mk('defs'),clip=mk('clipPath',{id:`clip-${id}`});clip.appendChild(mk('path',{d:'M 8 3 H92 V329 Q92 391 50 398 Q8 391 8 329 Z'}));defs.appendChild(clip);tube.forEach((k,i)=>{const e=E[k],g=mk('linearGradient',{id:`g-${id}-${i}`,x1:'0',x2:'1'});g.append(mk('stop',{offset:'0%','stop-color':e.c2}),mk('stop',{offset:'42%','stop-color':e.c}),mk('stop',{offset:'100%','stop-color':e.c2}));defs.appendChild(g)});svg.appendChild(defs);const stack=mk('g',{class:'fluid-stack','clip-path':`url(#clip-${id})`}),segH=94,base=395;tube.forEach((k,i)=>{const top=base-(i+1)*segH,amp=i===tube.length-1?5.5:2.2,phase=i%2?1.2:-1.2,grp=mk('g',{class:'fluid-segment','data-seg':i});grp.appendChild(mk('path',{class:'fluid-fill',d:`${wave(top,amp,phase)} L93 399 L7 399 Z`,fill:`url(#g-${id}-${i})`}));grp.appendChild(mk('path',{class:i===tube.length-1?'fluid-surface':'fluid-interface',d:wave(top,amp*.72,phase*.35)}));for(let b=0;b<3;b++){const q=mk('circle',{class:'fluid-bubble',cx:20+Math.random()*60,cy:Math.min(385,top+20+Math.random()*54),r:1.4+Math.random()*2.1});q.style.setProperty('--dur',`${2.8+Math.random()*2.5}s`);q.style.setProperty('--delay',`${-Math.random()*2.4}s`);stack.appendChild(q)}stack.appendChild(grp);const txt=mk('text',{class:'fluid-label',x:50,y:top+54,'text-anchor':'middle','data-label':i});txt.textContent=E[k].s;svg.appendChild(txt)});svg.insertBefore(stack,svg.querySelector('text'));const glass=mk('path',{class:'fluid-glass-glint',d:'M16 16 C12 112 14 278 25 344'});svg.appendChild(glass);return svg}
function render(){const board=$('board');board.innerHTML='';S.tubes.forEach((tube,i)=>{const wrap=document.createElement('div');wrap.className='tube-wrap';const el=document.createElement('div');el.className='tube'+(i===S.sel?' selected':'');if(isLocked(i)){el.className+=' contaminated';el.dataset.contam=S.contam[i]}else if(S.sel>=0&&i!==S.sel){const sec=secretFor(S.sel,i),haz=hazardFor(S.sel,i);if(haz)el.className+=' risky';else el.className+=(legal(S.tubes,S.sel,i)||sec)?' valid':' dim'}const inn=document.createElement('div');inn.className='tube-inner v21';inn.appendChild(fluidSvg(tube,`${Date.now().toString(36)}-${i}`));el.appendChild(inn);wrap.appendChild(el);let sx=0,sy=0;wrap.addEventListener('pointerdown',ev=>{sx=ev.clientX;sy=ev.clientY;wrap.classList.add('pressed')},{passive:true});wrap.addEventListener('pointercancel',()=>wrap.classList.remove('pressed'));wrap.addEventListener('pointerup',ev=>{wrap.classList.remove('pressed');if(Math.hypot(ev.clientX-sx,ev.clientY-sy)<12){ev.preventDefault();tap(i)}},{passive:false});board.appendChild(wrap)});$('moves').textContent=S.moves;$('levelTitle').textContent=`Дослід ${S.level}`;$('levelSub').textContent='Реагенти: '+[...new Set(S.tubes.flat())].map(k=>E[k].s).join(', ');$('footerLevel').textContent=`Рівень ${S.level} з 50 ›`;$('undoBadge').textContent=S.undo;$('shuffleBadge').textContent=S.shuffle;$('hintBadge').textContent=S.hints;rankUI();stationUI();save()}
function start(level){S.level=Math.max(1,level);syncUnlocks();S.tubes=build();S.sel=-1;S.hist=[];S.moves=Math.max(22,S.par+12);S.undo=3;S.shuffle=3;S.hints=3;S.extra=false;S.busy=false;S.contam={};render()}
function makeStream(x1,y1,x2,y2,color,duration=1080){const svg=mk('svg',{class:'liquid-stream-svg'}),p=mk('path',{class:'liquid-stream-path',d:`M ${x1} ${y1} C ${x1+4} ${y1+54},${x2-5} ${y2-42},${x2} ${y2}`});p.style.setProperty('--pourColor',color);svg.appendChild(p);document.body.appendChild(svg);const len=p.getTotalLength();p.style.strokeDasharray=len;p.style.strokeDashoffset=len;p.animate([{strokeDashoffset:len,opacity:0},{strokeDashoffset:0,opacity:1,offset:.16},{strokeDashoffset:0,opacity:1,offset:.82},{strokeDashoffset:-len*.2,opacity:0}],{duration,easing:'ease-in-out'});setTimeout(()=>svg.remove(),duration+80)}
function angle(el){const t=getComputedStyle(el).transform;if(!t||t==='none')return 0;try{const m=new DOMMatrixReadOnly(t);return Math.atan2(m.b,m.a)*180/Math.PI}catch{return 0}}
function animateFluidGhost(g){let alive=true;const loop=()=>{if(!alive||!g.isConnected)return;const a=angle(g),stack=g.querySelector('.fluid-stack');if(stack)stack.setAttribute('transform',`rotate(${clamp(-a*.92,-64,64)} 50 215) translate(0 ${Math.abs(a)*.10})`);requestAnimationFrame(loop)};requestAnimationFrame(loop);return()=>alive=false}
function liveVolume(a,b,n,p){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst)return;const sgs=[...src.querySelectorAll('.fluid-segment')],sl=[...src.querySelectorAll('.fluid-label')];const moved=n*p;for(let j=0;j<n;j++){const idx=sgs.length-1-j,local=clamp(moved-j,0,1);if(sgs[idx]){sgs[idx].style.opacity=String(1-local);sgs[idx].style.transform=`translateY(${local*16}px) scaleY(${1-local*.28})`;if(sl[idx])sl[idx].style.opacity=String(1-local)}}const stack=dst.querySelector('.fluid-stack');if(stack)stack.style.transform=`translateY(${-Math.sin(p*Math.PI)*2.8}px) scaleY(${1+Math.sin(p*Math.PI)*.018})`}
function animatePour(a,b,n,color,done){const tubes=[...document.querySelectorAll('.tube')],src=tubes[a],dst=tubes[b];if(!src||!dst||!src.animate){done();return}const A=src.getBoundingClientRect(),B=dst.getBoundingClientRect(),dir=B.left>A.left?1:-1,g=src.cloneNode(true);g.className='tube pour-ghost v21-ghost';Object.assign(g.style,{left:A.left+'px',top:A.top+'px',width:A.width+'px',height:A.height+'px'});document.body.appendChild(g);src.style.opacity='.12';const stopFluid=animateFluidGhost(g),dx=(B.left+B.width/2)-(A.left+A.width/2)-dir*9,dy=(B.top-A.top)-A.height*.43,tilt=dir*64,duration=2250;const an=g.animate([{transform:'translate3d(0,0,0) rotate(0)',offset:0},{transform:`translate3d(${dx*.38}px,${dy*.33}px,0) rotate(${tilt*.10}deg)`,offset:.2},{transform:`translate3d(${dx*.82}px,${dy*.82}px,0) rotate(${tilt*.54}deg)`,offset:.36},{transform:`translate3d(${dx}px,${dy}px,0) rotate(${tilt}deg)`,offset:.47},{transform:`translate3d(${dx}px,${dy+2}px,0) rotate(${tilt}deg)`,offset:.78},{transform:`translate3d(${dx*.62}px,${dy*.5}px,0) rotate(${tilt*.18}deg)`,offset:.91},{transform:'translate3d(0,0,0) rotate(0)',offset:1}],{duration,easing:'cubic-bezier(.22,.64,.18,1)',fill:'forwards'});const pourStart=930,pourDur=950;setTimeout(()=>{const x=B.left+B.width/2,y=B.top+8;makeStream(x-dir*17,y-72,x,y,color,pourDur);dst.classList.add('receiving');haptic(12);const t0=performance.now();const tick=now=>{const p=clamp((now-t0)/pourDur,0,1);liveVolume(a,b,n,p);if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);setTimeout(()=>dst.classList.remove('receiving'),1150)},pourStart);Promise.resolve(an.finished).catch(()=>{}).finally(()=>{stopFluid();src.style.opacity='';g.remove();done()})}
function fxAt(i,color,kind='burst'){const tube=document.querySelectorAll('.tube')[i];if(!tube)return;const r=tube.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height*.45;const ring=document.createElement('i');ring.className='reaction-fx reaction-ring';ring.style.left=x+'px';ring.style.top=y+'px';ring.style.setProperty('--fx',color);document.body.appendChild(ring);setTimeout(()=>ring.remove(),1000);for(let n=0;n<14;n++){const p=document.createElement('i');p.className='reaction-fx '+(kind==='crystal'?'reaction-crystal':'reaction-particle');p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--fx',color);p.style.setProperty('--dx',(-55+Math.random()*110)+'px');p.style.setProperty('--dy',(-65+Math.random()*100)+'px');p.style.setProperty('--rot',(-90+Math.random()*180)+'deg');document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}}
function completeTube(i){const t=S.tubes[i];if(t.length!==CAP||!t.every(x=>x===t[0]))return Promise.resolve(false);const key=t[0],color=E[key].c,tube=document.querySelectorAll('.tube')[i];S.busy=true;tube?.classList.add('completing');haptic([12,35,18]);return new Promise(res=>{setTimeout(()=>{fxAt(i,color,key==='rose'||key==='citrine'?'crystal':'burst');tube?.classList.add('completion-burst');S.gold+=12;setTimeout(()=>{S.tubes[i]=[];delete S.contam[i];S.busy=false;toast(`${E[key].n}: блок завершено · +12 ◆`);render();res(true)},650)},900)})}
function pairFor(a,b){if(a<0||b<0||a===b||isLocked(a)||isLocked(b))return null;const A=S.tubes[a],B=S.tubes[b];if(!A?.length||!B?.length)return null;return[E[A.at(-1)].s,E[B.at(-1)].s]}
function secretFor(a,b){const p=pairFor(a,b);return p?SECRETS.find(s=>s.pair.every(x=>p.includes(x)))||null:null}
function hazardFor(a,b){const p=pairFor(a,b);return p?HAZARDS.find(h=>h.pair.every(x=>p.includes(x)))||null:null}
function banner(title,text,cls='secret-banner'){const d=document.createElement('div');d.className=cls;d.innerHTML=`<b>${title}</b>${text}`;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function tickContam(except=-1){for(const k of Object.keys(S.contam)){const i=+k;if(i===except)continue;S.contam[i]--;if(S.contam[i]<=0){delete S.contam[i];toast('Контамінація нейтралізована')}}}
function doSecret(a,b,sec){S.busy=true;S.hist.push(clone(S.tubes));animatePour(a,b,1,sec.fx,()=>{S.tubes[a].pop();S.tubes[b].pop();S.moves--;S.gold+=sec.bonus;let artifact=null;if(Math.random()<.28){artifact=sec.artifact;S.artifacts.push({name:artifact,level:S.level,ts:Date.now()});S.nug+=1}S.sel=-1;fxAt(b,sec.fx,sec.kind);banner(sec.title,`+${sec.bonus} ◆${artifact?` · АРТЕФАКТ: ${artifact}`:''}`);tickContam();S.busy=false;save();haptic([10,28,14]);setTimeout(()=>{render();end()},760)})}
function doHazard(a,b,haz){S.busy=true;S.hist.push(clone(S.tubes));animatePour(a,b,1,haz.fx,()=>{S.tubes[a].pop();S.tubes[b].pop();S.moves--;S.hazards++;S.sel=-1;fxAt(b,haz.fx,'burst');const win=Math.random()<.30;if(win){S.gold+=haz.jackpot;S.nug+=2;S.artifacts.push({name:haz.artifact,level:S.level,ts:Date.now(),risky:true});banner('РИЗИК ВИПРАВДАНО',`${haz.status} стабілізовано · +${haz.jackpot} ◆ · +2 ◇ · АРТЕФАКТ: ${haz.artifact}`,'risk-banner jackpot');haptic([12,30,24])}else{S.gold=Math.max(0,S.gold-haz.penalty);S.contam[b]=haz.contam;banner(haz.title,`${haz.status} · −${haz.penalty} ◆ · пробірка заблокована на ${haz.contam} ходи`,'risk-banner');haptic([20,35,20])}tickContam(b);S.busy=false;save();setTimeout(()=>{render();end()},980)})}
async function tap(i){if(S.busy)return;if(isLocked(i)){toast(`☣ Контамінація: ще ${S.contam[i]} ходи`);haptic([16,28,16]);return}if(S.sel<0){if(!S.tubes[i].length)return;S.sel=i;$('hint').textContent='Зелене — безпечно · помаранчеве — ризик';haptic(8);render();return}if(S.sel===i){S.sel=-1;render();return}const a=S.sel,n=legal(S.tubes,a,i),sec=secretFor(a,i),haz=hazardFor(a,i);if(!n&&haz){doHazard(a,i,haz);return}if(!n&&sec){doSecret(a,i,sec);return}if(!n){document.querySelectorAll('.tube')[i]?.classList.add('shake');haptic([18,30,18]);setTimeout(()=>render(),320);S.sel=-1;return}const next=clone(S.tubes);for(let k=0;k<n;k++)next[i].push(next[a].pop());S.busy=true;S.hist.push(clone(S.tubes));const color=E[S.tubes[a].at(-1)].c;animatePour(a,i,n,color,async()=>{S.tubes=next;S.moves--;S.sel=-1;tickContam();S.busy=false;render();await completeTube(i);end()})}
function end(){if(cleared()){const rw=40+S.level*5,xp=20+S.level*3;S.gold+=rw;S.xp+=xp;save();$('winReward').textContent=`+${rw} ◆`;$('winXp').textContent=`+${xp} XP`;$('win').classList.add('show');haptic([12,28,20,28,26])}else if(S.moves<=0)$('lose').classList.add('show')}
function bestHint(){for(let a=0;a<S.tubes.length;a++)for(let b=0;b<S.tubes.length;b++)if(legal(S.tubes,a,b))return[a,b];return null}
$('undo').onclick=()=>{if(S.busy)return;if(S.undo<=0)return toast('Скасування закінчились');if(!S.hist.length)return toast('Немає ходу для скасування');S.tubes=S.hist.pop();S.contam={};S.undo--;S.moves++;S.sel=-1;haptic(8);render()};
$('shuffle').onclick=()=>{if(S.busy)return;if(S.shuffle<=0)return toast('Перемішування закінчились');S.shuffle--;S.tubes=build(Date.now()%997);S.contam={};S.hist=[];S.moves=Math.max(S.moves,S.par+10);S.sel=-1;haptic(10);render();toast('Новий розклад · контамінацію очищено')};
$('addTube').onclick=()=>{if(S.busy)return;if(S.extra)return toast('Додаткова колба вже встановлена');S.tubes.push([]);S.extra=true;haptic(8);render();toast('Додано порожню колбу')};
$('hintBtn').onclick=()=>{if(S.busy)return;if(S.hints<=0)return toast('Підказки закінчились');const h=bestHint();if(!h)return toast('Спробуй іншу комбінацію або перемішай');S.hints--;S.sel=h[0];haptic(6);render();toast(`Підказка: ${h[0]+1} → ${h[1]+1}`)};
$('station').onclick=()=>{if(S.busy)return;const r=reaction(),need=r.need[S.reactionStep];if(S.sel<0)return toast(`Обери зразок ${need}`);if(isLocked(S.sel))return toast('Контаміновану пробірку не можна використати');const tube=S.tubes[S.sel],sym=tube.length?E[tube.at(-1)].s:null;if(sym!==need){S.sel=-1;render();return toast(`Для ${r.formula} потрібен ${need}`)}S.reactionStep++;S.sel=-1;if(S.reactionStep>=r.need.length){S.reactionStep=0;S.reactionIndex++;S.gold+=15;save();toast(`Синтезовано ${r.formula} · +15 ◆`);haptic([10,25,14])}else toast(`${sym} додано до синтезу`);render()};
$('next').onclick=()=>{$('win').classList.remove('show');start(S.level+1)};$('more').onclick=()=>{$('lose').classList.remove('show');S.moves+=3;render()};$('retry').onclick=()=>{$('lose').classList.remove('show');start(S.level)};$('sound').onclick=()=>{S.muted=!S.muted;localStorage.cl9_muted=S.muted?'1':'0';$('sound').textContent=S.muted?'🔇':'🔊'};$('settings').onclick=()=>$('settingsPanel').classList.add('show');$('closeSettings').onclick=()=>$('settingsPanel').classList.remove('show');
start(S.level);
})();