import {test} from 'node:test';import assert from 'node:assert/strict';
import {freshCity,normalizeCity,deliverDiscovery,step,TYPES,stats} from '../dist/settlement-model.js';
import {ensureStory,choosePath,claimStory,collectArtifact,artifactError,STORIES,ARTIFACTS,storyProduction} from '../dist/city-story.js';
import {SUBSTANCES,REACTION_MODES,conditionReady,createMission,formulaMove,settleMission} from '../dist/mission.js';
import {normalizePreferences,makeBackup,restoreBackup} from '../dist/preferences.js';
import {lightCycle} from '../dist/settlement-life.js';
test('legacy saves keep buildings/resources while new story choices and relics survive reload',()=>{const c=freshCity();ensureStory(c);c.lastLevel=4;assert(claimStory(c));assert(choosePath(c,'science'));assert(!choosePath(c,'trade'));assert(collectArtifact(c,'compass'));const loaded=normalizeCity(JSON.parse(JSON.stringify(c)),4);assert.deepEqual(loaded.story,c.story);assert.deepEqual(loaded.resources,c.resources);assert.equal(loaded.buildings.length,c.buildings.length);assert.equal(storyProduction(loaded,{type:'school'}),1.25);assert.equal(storyProduction(loaded,{type:'farm'}),1)});
test('story/relic rewards cannot be claimed twice or before conditions; routes enforce territorial discovery',()=>{const c=freshCity();ensureStory(c);assert(!claimStory(c));assert(!collectArtifact(c,'compass'));c.lastLevel=4;assert(claimStory(c));const coins=c.pendingCoins;assert(!claimStory(c));assert.equal(c.pendingCoins,coins);assert(collectArtifact(c,'compass'));const after=JSON.stringify(c.resources);assert(!collectArtifact(c,'compass'));assert.equal(JSON.stringify(c.resources),after);assert.match(artifactError(c,'heart'),/територію/);assert(!choosePath(c,'__proto__'));});
test('complete campaign and every artifact can be reached on each development path',()=>{for(const path of ['science','garden','trade']){const c=freshCity();ensureStory(c);choosePath(c,path);c.seconds=100;c.extent=20;c.lastLevel=80;c.tech=['water','steel','battery'];c.completedExpeditions=3;c.completedVoyages=3;c.resources.food=300;c.discoveries=SUBSTANCES.map(q=>q.id);c.buildings=['quarry','well','school','university','ranch','fishery','energy'].map((type,i)=>({id:i+1,type,x:i,y:4,level:3,ready:0}));for(let i=0;i<STORIES.length+2;i++){for(const a of ARTIFACTS)collectArtifact(c,a.id);claimStory(c);}assert.equal(c.story.claimed.length,12,path);assert.equal(c.story.artifacts.length,6,path)}});
test('all twelve formulas have an accessible solution and accept only their declared modes',()=>{const pool=[...new Set(SUBSTANCES.flatMap(q=>q.atoms)),'Cl','Na','Au'];for(const q of SUBSTANCES){let {tubes:t,moves}=createMission(q,Math.max(60,q.level),pool);assert(t.every(t=>t.length<=4));let claimed=false,used=0;while(!claimed){let a=t.findIndex((v,i)=>i>0&&formulaMove(t,i,0,q));assert(a>0,q.id);const r=settleMission(formulaMove(t,a,0,q),q,claimed);t=r.tubes;claimed=r.formula;used++;}while(t.some(x=>x.length)){let done=false;for(let a=1;a<t.length&&!done;a++)for(let b=1;b<t.length;b++){if(!t[b].length)continue;const next=formulaMove(t,a,b,q);if(!next)continue;t=settleMission(next,q,true).tubes;used++;done=true;break;}assert(done,q.id);}assert(used<=moves,q.id);if(q.condition){assert(conditionReady(q,q.condition));assert(!conditionReady(q,'none'));assert(Object.hasOwn(REACTION_MODES,q.condition));}}});
test('new discoveries reward research once and persist through legacy normalizer',()=>{const c=freshCity();const n=c.resources.research;assert(deliverDiscovery(c,'oxygen'));assert(!deliverDiscovery(c,'oxygen'));assert.equal(c.resources.research,n+3);assert(normalizeCity(c).discoveries.includes('oxygen'));assert(!deliverDiscovery(c,'invalid'));});
function storage(){const m=new Map();return {get length(){return m.size},key:i=>[...m.keys()][i],getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}}
test('backup migrates progress and preferences and rejects malformed files without modifying data',()=>{const s=storage();s.setItem('chemlab_v50',JSON.stringify({level:42}));s.setItem('chemlab_settlement_v2',JSON.stringify(freshCity()));s.setItem('other-service','private');s.setItem('chemlab_preferences_v1',JSON.stringify({cityEnabled:false}));const file=makeBackup(s);assert(!file.values['other-service']);const target=storage();restoreBackup(file,target);assert.equal(target.getItem('chemlab_v50'),s.getItem('chemlab_v50'));assert.equal(normalizePreferences(JSON.parse(target.getItem('chemlab_preferences_v1'))).cityEnabled,false);assert.throws(()=>restoreBackup({...file,values:{chemlab_v50:'broken'}},target));assert.equal(target.getItem('chemlab_v50'),s.getItem('chemlab_v50'))});
test('ambient light is bounded and reduced motion disables day/night cycling',()=>{for(let t=0;t<1200;t++){const v=lightCycle(t);assert(v.night>=0&&v.night<=.2);assert.deepEqual(lightCycle(t,true),{night:0,warm:0,label:'День'})}});
test('science bonus delivers fractional research instead of losing the 25 percent to rounding',()=>{
 const c=freshCity();ensureStory(c);choosePath(c,'science');
 c.buildings.push({id:5,type:'school',x:3,y:5,level:1,ready:0});c.nextId=6;
 for(let i=0;i<500;i++)step(c,.1);
 assert(c.resources.research>2);
 assert.notEqual(c.resources.research%1,0,'fractional research is retained');
 const restored=normalizeCity(JSON.parse(JSON.stringify(c)));assert(restored.resources.research>=c.resources.research);
});
