import {test} from 'node:test';import assert from 'node:assert/strict';
import {freshCity,normalizeCity,deliverDiscovery,stats,step,research,onChemistryWin,build,upgrade,expand,terrain,route} from '../dist/settlement-model.js';
const run=(c,n)=>{for(let i=0;i<n*10;i++)step(c,.1)};
test('workers travel and deliver resources; construction persists independently of chemical saves',()=>{const c=freshCity();run(c,40);assert(c.resources.wood>65);assert(c.resources.food>55);assert(c.agents.some(a=>a.job));assert.equal(build(c,'house',7,4),'');const restored=normalizeCity(JSON.parse(JSON.stringify(c)));assert.equal(restored.buildings.length,5);assert.equal(restored.resources.wood,c.resources.wood+c.agents.reduce((n,a)=>n+(a.state==='return'?a.cargo.wood||0:0),0));assert.deepEqual(normalizeCity(restored).resources,restored.resources);assert.equal(restored.population,6)});
test('chemistry rewards and settlers are idempotent, technologies need both elements and research',()=>{const c=freshCity();assert.equal(research(c,'water',[]),false);assert(research(c,'water',['Cl']));assert(!research(c,'water',['Cl']));assert(onChemistryWin(c,2));const snapshot=JSON.stringify(c);assert(!onChemistryWin(c,2));assert.equal(JSON.stringify(c),snapshot);assert.equal(c.population,7);assert.equal(c.resources.research,2)});
test('invalid placements and unaffordable upgrades cannot spend resources',()=>{const c=freshCity();const initial=JSON.stringify(c);assert(build(c,'mine',2,2));assert.equal(JSON.stringify(c),initial);assert(build(c,'well',6,6));assert.equal(JSON.stringify(c),initial);assert.equal(build(c,'road',4,4),'Ділянка вже зайнята');c.resources.wood=0;assert(!upgrade(c,1));assert(!expand(c))});
test('water and housing have functional effects on health and births',()=>{const c=freshCity();c.resources.wood=500;c.resources.stone=500;assert(research(c,'water',['Cl']));assert.equal(build(c,'well',6,5),'');run(c,8);assert(stats(c).health>=75);c.resources.food=500;run(c,115);assert.equal(c.births,1);assert.equal(c.population,7)});
test('industry requires inputs, delivers outputs and trucks require connected roads',()=>{const c=freshCity();c.tech=['steel','motor'];for(const k in c.resources)c.resources[k]=500;assert.equal(build(c,'factory',6,4),'');assert.equal(build(c,'road',5,5),'');assert.equal(build(c,'road',6,5),'');const goods=c.resources.goods;run(c,40);assert(c.resources.goods>goods);assert(c.agents.some(a=>a.truck));c.resources.metal=0;run(c,30);const after=c.resources.goods;run(c,40);assert.equal(c.resources.goods,after)});
test('route avoids river and buildings; expansion reveals resource deposits',()=>{const c=freshCity();assert.equal(route(c,{x:4,y:5},{x:3,y:4}),null);const r=route(c,{x:4,y:5},{x:7,y:7});assert(r&&r.every(p=>terrain(p.x,p.y)!=='water'));for(const k in c.resources)c.resources[k]=500;assert(expand(c));assert.equal(c.extent,12);c.extent=20;assert(!expand(c));});

test('formula discoveries persist once and improve real production and future research',()=>{const plain=freshCity(),boost=freshCity();assert(deliverDiscovery(boost,'salt'));assert(!deliverDiscovery(boost,'salt'));assert(deliverDiscovery(boost,'glass'));run(plain,40);run(boost,40);assert(boost.resources.food>plain.resources.food);const restored=normalizeCity(boost);assert.deepEqual(restored.discoveries,['salt','glass']);const before=restored.resources.research;assert(onChemistryWin(restored,2));assert.equal(restored.resources.research,before+3);assert(!onChemistryWin(restored,2));assert(!deliverDiscovery(restored,'unknown'));});
